### ISSUE TITLE
vital.vim の内部ではなくて外部でモジュールが定義できる機能の提案

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/vital.vim#120]
現在、 vital.vim で使用する事ができるモジュールは vital.vim 本体に組み込まれている必要があります。
しかし、vital.vim のオレオレモジュールを提供したい場合、いきなり vital.vim 本体に組み込むのはなかなかに敷居が高いように感じられます。
これを unite-source などのように vital.vim 外部でモジュールが定義できるようになれば敷居が下がり、オレオレモジュールが作りやすくなるのではないでしょうか。
この機能が実装されれば、いくつかのわたしのライブラリ系プラグイン（reti.vim（無名関数ライクなライブラリ）、gift.vim（ウィンドウ番号周りのライブラリ））などを vital.vim のモジュールとして提供してみようかと考えています。
#### 気になっている点
- そもそも vital.vim の仕組みとして外部モジュールを利用する事は可能なのか
- 外部モジュールを vital.vim 本体で使用する事は実現できるか
  - vital-reti を vital.vim 本体で利用する事は可能なのか
- プラグインの実装を vital.vim のモジュールとして埋め込んでおいて、それを他のプラグインでも流用する事ができれば便利…？
  - e.g. twitter.vim（仮）に vital-twitter みたいなモジュールを定義して、他のプラグインで利用する
#### 課題
- バージョンの管理方法
  - 複数のコミットハッシュディレクトリに対応する必要がある
- `Vitalize` 時の指定をどうするか
  - e.g.`:Vitalize . vital.vim:Data.List foo.vim:Oreore.Module`
#### 実装内容
- vital#of() で外部モジュールの読み込み
- :Vitalize から外部モジュールの組み込み
#### 動作イメージ

``` vim
" 想定している環境
" Hoge プラグイン内に外部モジュール Foo が存在する
" Bar プラグイン内に vital.vim と Foo モジュールが組み込まれている

" vital.vim 本体から読み込み
let s:V = vital#of("vital")
let s:List = s:V.import("Data.List")

" vitla.vim 本体には組み込まれていないのでエラー
let s:Foo = s:V.import("Foo")


" Hoge プラグインから読み込み
let s:V = vital#of("Hoge")
" Hoge プラグインに
" vital.vim が組み込まれていれば OK
" 組み込まれていなければエラー
let s:s:List = s:V.import("Data.List")

" Hoge 内の Foo モジュールをインポート
let s:Foo = s:V.import("Foo")


" Bar プラグインからの読み込み
" vital.vim と Hoge の Foo モジュールが組み込まれている
let s:V = vital#of("Bar")

" 両方共インポート可能
let s:List = s:V.import("Data.List")
let s:Foo = s:V.import("Foo")
```

**Comment by tyru** [comment]
> Changes の機構は外部モジュールでは使えません。

@thinca これって今でもそうでしょうか？

**Comment by tyru** [comment]
あと、もし外部モジュールの作り方などを解説している情報(Wiki、help、ブログの記事、何でも可)があれば教えて頂きたいです。
