### ISSUE TITLE
spec がイケてないのをなんとかしたい

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#13]
現状 vital に同梱されている spec は、

- 手軽にコマンドラインから実行できない
- 結果がファイルに出る
- 結果が見づらい

などの様々な問題を抱えている。テストの実行が面倒だと誰もテストを実行しなくなる。
これを、改善するなり既存の別のテスティングフレームワークに置き換えるなりしたい。

**Comment by ujihisa** [comment]
わーい

**Comment by thinca** [comment]
:tada:

**Comment by kamichidu** [comment]
:congratulations:

**Comment by ujihisa** [comment]
感極まってきました。
