### ISSUE TITLE
s:_vital_loaded で排出した例外が潰される

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/vital.vim#194]
おそらく[ここ](https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__latest__.vim#L235)が原因だと思うのですが、`s:_vital_loaded` で排出した例外が潰されています。
これでは `s:_vital_loaded` 時に問題があった場合、原因を調べるのが困難な為、せめて『エラーになった』というメッセージだけでも出力されると嬉しいです。
（実際、まさにいま `s:_vital_loaded` 内でエラーが出ていたんですが原因を調べるまでに30分以上かかりました…

**Comment by thinca** [comment]
これが放置されてしまっているのって、どういう処理が適切なのかいまいちはっきりしていないからなので、できるだけ多くの意見がほしい感じです。
(とは言えあんまりなので適当でも何か対応した方がいい気がしている)

多分例外 or メッセージの2択になりそう。例外飛ばすならそもそも `try` しなくてもいいのでは説もある。

**Comment by rhysd** [comment]
時間が経っているので行がずれちゃってますが，[ここ](https://github.com/vim-jp/vital.vim/blob/a07740b6276b9d3d9057e7aa6d7fe667925c0bd1/autoload/vital/__latest__.vim#L252) ですよね？

今のままじゃまずいのは分かるのですが，何が問題になってこの issue が fix できないのかがよく分かっていないです．
`_vital_loaded` からの例外を握りつぶしてエラーメッセージに変えてしまうよりは，vital.vim の基本的なエラー時の規約（`vital: ...` をプレフィックスとした例外を投げる）に乗っ取るのが良いかなと思います．（一応 `_vital_loaded` でユーザが例外を投げたい場合にこまると思います．）

**Comment by thinca** [comment]
問題は特になくて、どうするべきかが決まっていない、というだけですね。
try を外す、でいいですかね? (そもそもなんでつけたかは忘れました…)

**Comment by rhysd** [comment]
確かに blame してコミットコメント見ても特に書いてないですね．

僕も単純に `try` を外すに1票です！

**Comment by thinca** [comment]
了解、#313 とコンフリクトする可能性が若干あるので、あちらがマージされたらササッとやっちゃいます。

**Comment by rhysd** [comment]
:dog::+1:
