### ISSUE TITLE
Replace vital spec with themis

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#207]
I discovered that a Vimmer made a good Vim script testing framework which is called themis https://github.com/thinca/vim-themis

I suggest that we abandon vital spec and use themis in vital as the standard testing framework.

TODOs if we decide to use themis

* Introduce themis
* Fix ci to use both vital spec and themis for graceful migration
* Replace all existing specs with themis
* Remove vital spec, and fix ci only to use themis

## Migration List

- [x] bitwise.vim               → __thinca__
- [x] data/string.vim           → __ujihisa__
- [x] data/list.vim             → __ujihisa__
- [x] data/base64.vim           → __mattn__
- [x] data/lazylist.vim         → __ujihisa__
- [x] data/dict.vim             → __thinca__
- [x] data/ordered_set.vim      → __tyru__
- [x] database/sqlite.vim       → __ujihisa__
- [x] date_time.vim             → __thinca__
- [x] interpreter/brainf__k.vim → __ujihisa__
- [x] locale/message.vim        → __thinca__
- [x] math.vim                  → __ujihisa__
- [x] option_parser.vim         → __rhysd__
- [x] prelude.vim               → __ujihisa__
- [x] process.vim               → __tyru__
- [ ] process_manager.vim       → __ujihisa__
- [x] random.vim                → __thinca__
- [x] random/xor128.vim         → __Linda\_pp__
- [x] text/lexer.vim            → __rbtnn__
- [x] text/table.vim            → __kamichidu__
- [x] text/ltsv.vim             → __thinca__
- [x] text/csv.vim              → __tyru__
- [x] vim/buffer.vim            → __thinca__
- [x] vim/message.vim           → __mattn__
- [x] vim/search.vim            → __ujihisa__
- [x] vim/compat.vim            → __mattn__
- [x] web/http.vim              → __mattn__
- [x] web/json.vim              → __mattn__
- [x] web/uri.vim               → __mattn__

## No test

- assertion.vim             __rbtnn__
- data/collection.vim       __ujihisa__
- data/tree.vim             __rbtnn__
- experimental/functor.vim  __tyru__
- lua/prelude.vim           __ujihisa__
- mapping.vim               __tyru__
- system/cache.vim          __ujihisa__
- system/file.vim           __Shougo__
- system/filepath.vim       __thinca__
- text/parser.vim           __rbtnn__
- vim/buffer_manager.vim    __tyru__
- web/html.vim              __mattn__
- web/xml                   __mattn__

**Comment by thinca** [comment]
時間あるときにちまちまと作業しています。できるだけ早くこの Issue 閉じたい…!!

**Comment by rhysd** [comment]
Web モジュールちまちまやってます．

**Comment by rhysd** [comment]
> Web モジュールちまちまやってます．

`Web` と `Data` の残りやりました．

**Comment by mattn** [comment]
犬がとうございます。

**Comment by rhysd** [comment]
:muscle::dog:

**Comment by rhysd** [comment]
本日移行終わったモジュールにチェック入れておきました．
後は ProcessManager だけですね（ﾁﾗｯﾁﾗｯ

**Comment by ujihisa** [comment]
> 後は ProcessManager だけですね（ﾁﾗｯﾁﾗｯ

ProcessManagerは #278 のあとdeprecatedになる予定なので、これでもうバッチリ説浮上かな?

**Comment by ujihisa** [comment]
@rhysd++ https://github.com/vim-jp/vital.vim/compare/614fc50b66aa...cd2d46a9555a

**Comment by rhysd** [comment]
:tada:
