### ISSUE TITLE
Change help filenames

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#219]
モジュール自体のファイル名や test のファイル名に合わせて、help のファイル名も変えたい。
理由は単に統一性のため。

例: `doc/vital-Data.List.txt`

実は、Vim 7.3.734 から、help 内でもサブディレクトリが使える。これを利用すると以下のようにもできる。

例: `doc/vital/Data/List.txt`

ただ、これはまだ若干使うのは早い気がするので、次のメジャーバージョンが出た辺りの方がいいかも。
2度変えるのは面倒なので、しばらくは我慢して次のメジャーバージョンが出た時に階層化するのでも良さそう。

**Comment by ujihisa** [comment]
vim7.5マイルストーンつけました (なんかマイルストーンの使い方が間違ってる気がしてきました)

**Comment by thinca** [comment]
#450 終わったらこちらもとりかかろうかな。
