### ISSUE TITLE
vital.vim's globpath() doesn't ignore &suffixes nor &wildignore

### ISSUE THREAD

**Issue by Shougo** [vim-jp/vital.vim#259]
globpath の第三引数が指定されていないので、globpath() が suffixes と wildignore を参照してしまいます。
ただ、このファイルを変更することがそもそも想定されておらず、vital.vim を使用している全プラグインを修正するのも難しいので、困った問題です。

関連： https://github.com/Shougo/neocomplete.vim/pull/372

**Comment by thinca** [comment]
ついにこの時が来てしまったか…。
関連: #40 #41

**Comment by Shougo** [comment]
> やるとして、今後更新が必要になってしまってからでいいかとは思います。ただ、その時のために対応を決めておくのは賛成です。

ああ、ついにその時が……

**Comment by ujihisa** [comment]
![](https://110bpm.files.wordpress.com/2012/06/artworks-000024880799-j8o4lw-original.jpg)

**Comment by haya14busa** [comment]
この issue 追ってなかったですが， #415 で `vital#pluginame#of`  や `vital#pluginame#import` といったシンタックスに変えれば解決できますね．

`vital#of` は `:Vitalize` しただけで #415 の恩恵を受けるので残す思いが個人的につよかったですが，すでに既知の問題があるのならちゃんと Changes かいて `autoload/vital.vim` は プラグインに同梱しないようにするのもありな気がしてきました．

**Comment by haya14busa** [comment]
というかこれ， `globpath`の第三引数ってすくなくとも 7.3 以前からありそう[1]だし，変更が一気に反映されなかったとしても直しておいたほうがよかったのでは....?

1:  [Vim script言語仕様の変更 · rbtnn/etc-about-vimscript Wiki](https://github.com/rbtnn/etc-about-vimscript/wiki/Vim-script%E8%A8%80%E8%AA%9E%E4%BB%95%E6%A7%98%E3%81%AE%E5%A4%89%E6%9B%B4) 調べ

**Comment by haya14busa** [comment]
```
Patch 7.2.051
Problem:    Can't avoid 'wildignore' and 'suffixes' for glob() and globpath().
Solution:   Add an extra argument to these functions. (Ingo Karkat)
Files:	    src/eval.c, src/ex_getln.c, src/proto/ex_getln.pro,
	    runtime/doc/eval.txt, runtime/doc/options.txt
```

たぶんこれですね．さすがに autoload/vital.vim が変わったせいで俺のvimは 7.2.051 以下だったから関数呼べなくなっておかしくなった!!! と言う人はいないのでは

**Comment by haya14busa** [comment]
> さすがに autoload/vital.vim が変わったせいで俺のvimは 7.2.051 以下だったから関数呼べなくなっておかしくなった!!! と言う人はいないのでは

そもそも __latest__.vim 内でglobpathの第3引数つかったので，互換性が崩れることはやはりないです

**Comment by haya14busa** [comment]
#421 はいった．
