### ISSUE TITLE
Data.List が uniq() を使用していない

### ISSUE THREAD

**Issue by Shougo** [vim-jp/vital.vim#262]
Vim 7.4.218 で uniq() が追加されましたが、vital.vimのData.Listモジュールでは使用していないようです。
これを使用したほうが効率化できると思うのですがどうでしょうか。

**Comment by rhysd** [comment]
これ，`uniq()` の意味が違うんじゃなかったでしたっけ？ `uniq()` は隣り合った同じ要素を1つにまとめるので `sort()` 前提ですが，`Data.List.uniq()` は __要素の順序を保存したまま__ 重複を省くとかだったような…

**Comment by rhysd** [comment]
それを把握した上で（互換性を壊してでも）`uniq()` を使うべきという提案だったらすみません．

**Comment by Shougo** [comment]
あれ、そういうことでしたっけ。だとすると、単純な置換えは難しいのかな。

**Comment by rhysd** [comment]
挙動的に互換性が崩れるので厳しそうです．`uniq_unstable()` みたいなのを新たに生やしてそこで `sort(uniq(...))` を使って実装するのは良いと思います．

**Comment by Shougo** [comment]
問題は新しく関数を追加するほどの利点があるかですね。

**Comment by rhysd** [comment]
はい，そう思います．
僕自身は今のところ必要性を感じていないです．

**Comment by Shougo** [comment]
ちょっと現段階では意味がなさそうです。closeします。

**Comment by ujihisa** [comment]
しかしこれ、勘違いしやすいと思うので、vim本体のuniqについてもvitalのuniqのdocで言及すると便利そうです。

**Comment by mattn** [comment]
現状の vital に入ってるやつが uniq じゃなくて squash なんじゃなかろうか。
