### ISSUE TITLE
Document the undocumented modules

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#279]
* `autoload/vital/__latest__/Text/Sexp.vim`
* `autoload/vital/__latest__/Web/URI.vim`
* `autoload/vital/__latest__/Interpreter/Brainf__k.vim`
* Vital core (import()とか)

がundocumentedです。うち`Text.Sexp`と`Brainf__k`はもともと僕が作ったものなので、僕が担当します。残りどなたかお願いしますー

(前スレ https://github.com/vim-jp/vital.vim/issues/5 )

## 上記リストの生成方法

```ruby
xs = Dir.glob('autoload/vital/__latest__/**/*.vim').map {|path|
  v = path.sub('autoload/vital/__latest__/', '').downcase.
    sub('-', '').sub('/', '-').sub(/\.vim$/, '')
  [v, path]
}.to_h
ys = Dir.glob('doc/vital-*.txt').map {|path|
  v = path.sub('doc/vital-', '').sub(/\.txt$/, '').
    sub('_', '')
  [v, path]
}.to_h

puts xs.reject {|k, v| ys[k] }.values
```

**Comment by ujihisa** [comment]
よくみたら`brainf__k`のdocありました。というわけで残り

* `autoload/vital/__latest__/Web/URI.vim`
* Vital core (import()とか)

おねがいしますー :repeat_one:

**Comment by ujihisa** [comment]
Web.URIを @tyru さんにアサインしてみました

**Comment by tyru** [comment]
これ、どういう経緯で自分になったんでしたっけ？

**Comment by crazymaster** [comment]
Web.URIのドキュメントがまだないので、導入した@tyruさんにアサインされたのかと。

**Comment by tyru** [comment]
あっ…すみません、メンテナ自分だった事を忘れてました…
了解です！

**Comment by ujihisa** [comment]
wktk

**Comment by tyru** [comment]
ドキュメント追加しました。
closeしちゃって構いませんかね？ > @ujihisa

**Comment by ujihisa** [comment]
tyru++ (//

**Comment by tyru** [comment]
肯定と受け取りました！

**Comment by rhysd** [comment]
:dog::tada:

**Comment by ujihisa** [comment]
![](http://www.rtoronto.ca/wp-content/uploads/2015/03/Best-Sushi-in-Toronto.jpg)

**Comment by tyru** [comment]
:sushi: :tada:
