### ISSUE TITLE
exception message convention

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#285]
``` vim
throw 'vital: Data.List: ...'
```

みたいな例外メッセージをvitalの標準としているものの、 https://github.com/vim-jp/vital.vim/pull/284 の過程でちょこちょこそれにしたがっていないのを見つけました。(当時二箇所だけしかないと思い)一部は←で修正していますが、他にもあるぽいので独立したissueたてます。

**Comment by aomoriringo** [comment]
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Text/Lexer.vim#L27
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Text/Parser.vim#L6
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Prelude.vim#L256
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Prelude.vim#L262
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/System/File.vim#L59
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Experimental/Functor.vim#L45
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Data/LazyList.vim#L29
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Data/List.vim#L228
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Data/List.vim#L241
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/ProcessManager.vim#L56
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Process.vim#L56
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Web/XML.vim#L285
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Web/URI.vim#L259
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Interpreter/Brainf__k.vim#L33
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Interpreter/Brainf__k.vim#L41
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/ConcurrentProcess.vim#L170
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Random/Xor128.vim#L59
https://github.com/vim-jp/vital.vim/blob/3d12fa2/autoload/vital/__latest__/Lua/Prelude.vim#L18

以下のファイルは、上記に挙げた行以外に複数箇所あります。
- System/File.vim
- ProcessManager.vim
- Process.vim
- Web/URI.vim

**Comment by thinca** [comment]
#470 で大半が直されたとのウワサ。

**Comment by thinca** [comment]
@haya14busa @rhysd 私自身確認してないんですが、全て修正されたということであってるでしょうか? だとしたらこれ閉じちゃいます。

**Comment by haya14busa** [comment]
o.k.

**Comment by rhysd** [comment]
#470 と #471 で全て修正済みです :tada:
