### ISSUE TITLE
RFC: cache

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/vital.vim#288]
現在 `Vital.System.Cache` にファイルベースのキャッシュシステムが入っていますが名前空間的にどうなのか？という気がします（インスタンスキャッシュとかLRUとかいろいろ増やしたくなった時に困る）。 

加えてキャッシュシステムは簡単に切り替えられたほうが何かと便利なので https://github.com/lambdalisue/vital-System-Cache-Unified というものを外部モジュールとして作成しました。
皆さんの同意が得られれば上記のものから `Vital.System.Cache` 依存をなくしてコミットしたいと思っているのですがどうでしょう？

以下、最終形の理想的使い方

```vim
let s:Cache = s:V.import('Vital.System.Cache')

" Instance
let s:cache = s:Cache.new('simple')
" 下記と同意
" let s:cache = s:V.import('Vital.System.Cache.Simple').new()
call s:cache.set('hello', 'foo')
echo s:cache.get('hello')
" foo

" File
let s:cache = s:Cache.new('file', { 'cache_dir': '~/.cache' })
" 下記と同意
" let s:cache = s:V.import('Vital.System.Cache.File').new({ 'cache_dir': '~/.cache' })
call s:cache.set('hello', 'foo')
echo s:cache.get('hello')
" foo

" Dummy
let s:cache = s:Cache.new('dummy')
" 下記と同意
" let s:cache = s:V.import('Vital.System.Cache.Dummy').new()
call s:cache.set('hello', 'foo')
echo s:cache.get('hello')
" <empty>


" このようにいろんなタイプを増やせる + ユーザーが簡単にキャッシュメカニズムを変えられる
```

ただ、これをするには `Vital.System.Cache` の意味を変更しないとならないため @Shougo さんが困りそう。

ご意見お待ちしています。

**Comment by Shougo** [comment]
こんにちは。インタフェースを変えてしまうと、既存のプラグインが壊れてしまうので、
私としては、現在のインタフェースが名前を変えるだけで残るならば、新しいキャッシュ機構を作ることには賛成です。

**Comment by thinca** [comment]
そもそも `System.Cache` と言う名前がアレなので(`System` 関係ない)、全く別の場所に別の名前で追加するのはどうでしょうか。具体的な名前についてはいい案はないのですが…。

**Comment by mattn** [comment]
System をどう捉えるかによりますが、.NET だと System.Runtime.Caching すね。

On 4/9/15, thinca <notifications@github.com> wrote:
> そもそも `System.Cache` と言う名前がアレなので(`System`
> 関係ない)、全く別の場所に別の名前で追加するのはどうでしょうか。具体的な名前についてはいい案はないのですが…。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/vital.vim/issues/288#issuecomment-91187915


-- 
- Yasuhiro Matsumoto

**Comment by lambdalisue** [comment]
> こんにちは。インタフェースを変えてしまうと、既存のプラグインが壊れてしまうので、
私としては、現在のインタフェースが名前を変えるだけで残るならば、新しいキャッシュ機構を作ることには賛成です。

`System.Cache` のインターフェイスを残すとなるならば `System.Cache.File` に同じインターフェイスを作るという形になると思います（`System.Cache.XXX`はインスタンス化して利用することを前提としているため非インスタンスメソッドを追加するのは問題ないと思うので）。

> そもそも System.Cache と言う名前がアレなので(System 関係ない)、全く別の場所に別の名前で追加するのはどうでしょうか。具体的な名前についてはいい案はないのですが…。

`Data.Cache` とかですかね。もしくは `Cache` でもいいかもしれません。

**Comment by lambdalisue** [comment]
名前空間アイディア
- System.Cache
- System.Runtime.Caching
- Data.Cache
- Cache

個人的には `System.Cache` けっこうしっくりきます。

**Comment by rhysd** [comment]
`System.Cache` を使いたいという立場に立つと，現在のを `System.Cache.Deprecated` に移してしまうのはどうでしょうか．これなら今までのプラグインも最小の変更で済むと思うのですが…

**Comment by Shougo** [comment]
> System.Cache をモジュール名として使いたいという立場に立つと，現在のを System.Cache.Deprecated に移してしまうのはどうでしょうか．これなら今までのプラグインも最小の変更で済むと思うのですが…（個人的にはテストすらないモジュールですし置き換えてしまっても良いと思ってますが）

気持ち的には置き換えたいのですが、移行コストがかなりかかってしまうのです……。

**Comment by rhysd** [comment]
> 気持ち的には置き換えたいのですが、移行コストがかなりかかってしまうのです……。
インポートするモジュール名を変えるだけだと思うのですが，具体的にどういうコストがかかるんですか？

**Comment by rhysd** [comment]
> > 気持ち的には置き換えたいのですが、移行コストがかなりかかってしまうのです……。

> インポートするモジュール名を変えるだけだと思うのですが，具体的にどういうコストがかかるんですか？

すみません，置き換えるというのは後者の実装を置き換えるのほうですね．

**Comment by lambdalisue** [comment]
個人的には

1. `System.Cache.readfile` や `System.Cache.writefile` などの主要なメソッドを `System.Cache.File` に移動し `System.Cache.File` はそれを利用してキャッシュ機構を他のキャッシュインスタンスと合うように作成 `get`, `set`, `have` など([現状](https://github.com/lambdalisue/vital-System-Cache-Unified/blob/master/autoload/vital/__latest__/System/Cache/File.vim#L62)でも利用しております)
2. `System.Cache.check_old_cache` などの特殊なメソッドはそのまま残して `System.Cache.warn_deprecated` が `0` 指定されない限り警告メッセージを出す
3. `System.Cache.readfile` など移動したメソッドは内部で `System.Cache.File.readfile` を呼び、上記と同様に警告を出す

という形がいいかなと思います。`System.Cache.Depercated` でも良いのですが使用者が全員ここを見ているとも限らないので `System.Cache.readfile` を警告なしに廃止するのはちょっとつらい。
この方法なら置き換えが難しいプラグイン作者はとりあえず `System.Cache.warn_deprecated = 0` を明示指定 or `System.Cache.File` を直接使うことで対応できるはずです。

**Comment by lambdalisue** [comment]
上記に特に大きな反論がない限り上記でPR送りますがどうします？（名前はとりあえず `System.Cache` で作ります。いい名前あったら変える）

**Comment by lambdalisue** [comment]
あーでも `System.Cache` ってドキュメントも無いしバリバリ使ってるのってここ見てる人だけかなー。それなら `warn_deprecated` みたいなの無しで廃止も有りか…

**Comment by Shougo** [comment]
インタフェースを単純に廃止するのでなければ、オプションを用意するか、名前を変えてそのまま残す方向のどちらでも良いです。それならプラグイン側でも対応できますので。

**Comment by rhysd** [comment]
その案で :+1: です．
（ちなみに JFYI ですが，Changes に書いておけば使用者が Vital モジュールを更新したときに通知されたと思います．）
