### ISSUE TITLE
Vim.BufferManager.opened() is not implemented

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#289]
```
Manager.opened({bufname})	*Vital.Vim.BufferManager-Manager.opened()*
	Not implemented yet.
```

docにある通り関数の用意はできているけど実装できていません。これ今後どういう予定なのでしょう

**Comment by ujihisa** [comment]
導入は @thinca さんによる 30ec2bec0fa90f873f26e4df1e5d65517e0a5977 と判明 (ファイル名変更が多くて見つけるのが難易度)

**Comment by ujihisa** [comment]
0d24d78da6f8bde448ba7b38f96b9a679b6142d7 で例外を投げるようになりました。

**Comment by crazymaster** [comment]
>http://lingr.com/room/vim/archives/2015/04/28#message-21754925
thinca: 今思い出したんだけど、BufferManager の opened() は未実装じゃないわあれ…あれはユーザーが上書きして使う hook 関数だ

**Comment by thinca** [comment]
あ、そういえばこれ Issue になってましたね…。ありがとうございます @crazymaster 
とりあえず例外投げるのやめて、doc に適切な説明を入れる必要がありますね。この Issue はそこをゴールにしましょう。
