### ISSUE TITLE
round() with digits

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#296]
https://github.com/vim-jp/issues/issues/726

これが仮に導入されたとしても古いvimでは動かないのでvitalに入れた方がよいと思うのですが、どのモジュールに入れるのがよいでしょうか

@aomoriringo

**Comment by aomoriringo** [comment]
普通に考えたらMath.round()かなあ。

**Comment by ujihisa** [comment]
wktk

**Comment by ujihisa** [comment]
aomoriringo++
