### ISSUE TITLE
DateTime.to に負数を指定できない？

### ISSUE THREAD

**Issue by delphinus35** [vim-jp/vital.vim#311]
```vim
let s:V = vital#of('vital')
let s:D = s:V.import('DateTime')
let s:today = s:D.now()
echo s:today.format('%F')
let s:hoge = s:today.to(-10, 0)
echo s:hoge.format('%F')
```

以上のスクリプトを実行すると、以下のように表示されます。

```
2015-08-08
2015-08-18
```

「10日前」を得たいがために、 `.to(-10, 0)` としているのですが、実際は「10日後」が返されているようです。

思うに、[ここ][]で負数×負数で必ず正数になってしまうのが原因ではないかと思うのですがどうでしょう？

[ここ]: https://github.com/vim-jp/vital.vim/blob/1dbb3887319984acc4a9ec83633bb4328dfab07a/autoload/vital/__latest__/DateTime.vim#L405

**Comment by thinca** [comment]
ありがとうございます！直しました！
