### ISSUE TITLE
AppVeyor でテスト回す

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#324]
Windows 環境テスト。
AppVeyor で org 的なことが要確認。
この辺りがそれっぽそう(まだ読んでない) http://www.appveyor.com/docs/team-setup
無理そうだったら最悪個人アカウントか共有アカウントになる(後者はパスワードの管理がアレになる)

**Comment by crazymaster** [comment]
権限的にはそちらが参考になるんですがvim-jp以下にするならこちらが参考になると思います。
http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

**Comment by thinca** [comment]
便利そうな情報！ありがとうございます！

**Comment by thinca** [comment]
軽く読んだ感じだと共有アカウントを作るしかなさげ…?

**Comment by crazymaster** [comment]
メアド/パスワードで vim-jp アカウントを作って、他のメンバーを Collaborator に追加する感じですかね。

GitHub teamsは使えなさそう。
>works only with "GitHub" sign in button. If you login with email/password teams membership is not applied.

**Comment by thinca** [comment]
これやるとしたら共用アカウントを取ることになりそうですけど、vim-jp のメールアドレスってあるのでしたっけ。 @koron さんが詳しい?

**Comment by koron** [comment]
数日中に対応します。

**Comment by thinca** [comment]
ありがとうございます！

**Comment by koron** [comment]
@thinca 調べました。

vital@vim-jp.org などを登録して、特定のメアドに転送できるように設定できます。
以前 vimconf@vim-jp.org を +vimconf@xxx に転送しましたよね。
アレと一緒です。

ですから、メアドの希望ユーザー名と転送先を言っていただければ設定します。

**Comment by thinca** [comment]
ありがとうございます。では、vital@vim-jp.org へのメールを、thinca+vital@gmail.com へ転送するよう設定してもらっても良いでしょうか?
他にも転送して欲しい人がいたら言ってもらう感じで。
現状、AppVeyor への登録のみに使う予定ですが、vital 関連で必要になったらそちらでも使う可能性があります。
また、AppVeyor への登録に使うパスワードは、ランダムで生成して vital@vim-jp.org 宛てに送ろうかと思います。

**Comment by koron** [comment]
転送設定を完了しました。

1つのアドレスを複数のメアドに転送できるかはやったことがないのでわかりませんが
メーリングリスト(google group)などのサービスを使うのが良いかもしれません。

**Comment by thinca** [comment]
テスト回るようになった。

**Comment by koron** [comment]
:+1:
