### ISSUE TITLE
Plugins Using vital.vim 情報がほしいような

### ISSUE THREAD

**Issue by kozo2** [vim-jp/vital.vim#327]
README.md に

**Comment by rbtnn** [comment]
「Plugins Using vital.vim 情報」がココに当たると思うのですが、具体的にどういう情報でしょうか？
https://github.com/vim-jp/vital.vim#lets-get-started

**Comment by thinca** [comment]
たぶんこれは、vital.vim を使っているプラグインのリストが欲しいってことだと思います。
:+1: ですが、利用者が編集できるように Wiki の方が良さそう。

**Comment by kozo2** [comment]
はい、「vital.vim を使っているプラグインのリストが欲しいってこと」を意図してました。
適当な書き方してしまいました。すんません。
なるほど、wikiの方が適していますね

**Comment by crazymaster** [comment]
既にwikiにあるっぽい(あんまり書かれてないけれど...)
https://github.com/vim-jp/vital.vim/wiki#plugins-that-use-vitalvim

**Comment by rbtnn** [comment]
「filetype:vital site:https://github.com/」でググれば....

**Comment by kozo2** [comment]
@crazymaster おお失礼しました。

**Comment by kozo2** [comment]
@rbtnn なるほど

**Comment by crazymaster** [comment]
既に vital.vim を使っているプラグインは大量にあるし、人力で書くのも大変すぎるので
検索のリンクを載せておくくらいで充分かなとは思います。

**Comment by haya14busa** [comment]
PRもﾏｯｼﾞされていて closable な気がするのでcloseします (please reopen if not)
