### ISSUE TITLE
DateTime unix_time return wrong value

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/vital.vim#334]
```vim
let V = vital#of('vital')
let T = V.import('DateTime')

let tz = T.timezone('+02:00')
let dt = T.from_date(2000, 8, 1, 0, 0, 0, tz)

let ts = dt.unix_time()

echomsg dt.to_string()
" 2000-08-01 00:00:00 +0200
echomsg T.from_unix_time(ts).to_string()
" 2000-07-31 07:00:00 +0900
echomsg T.from_unix_time(ts, tz).to_string()
" 2000-07-31 00:00:00 +0200
```

Executed in Japan (+09:00)

**Comment by lambdalisue** [comment]
https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__latest__/DateTime.vim#L350

**Comment by lambdalisue** [comment]
I'm not really sure but the issue still remain.

https://travis-ci.org/lambdalisue/vim-gita/jobs/89287014
https://github.com/lambdalisue/vim-gita/blob/91e9eaca559ea4e8c852b57383014f8adb508ca0/test/gita/features/blame.vimspec#L21
https://github.com/lambdalisue/vim-gita/blob/ed5aa91069ad38dfd3c11114b1cbd576f558efff/autoload/gita/features/blame.vim#L123

Any idea?

**Comment by thinca** [comment]
@lambdalisue `DateTime.strftime()` uses always current timezone(see help).  You should use `DateTime.format()` instead.

**Comment by lambdalisue** [comment]
I see that's why. Thanks!

**Comment by lambdalisue** [comment]
`DateTime.format({format}[, {locale})`....
