### ISSUE TITLE
Data.OrderedSet のテストが稀に落ちる

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#338]
https://github.com/vim-jp/vital.vim/blob/f4e5d4821de0a6483c24a2886344ddd9a6d63dc0/test/Data/OrderedSet.vimspec#L88-L89

この関数が何度か呼ばれる際に、実行中に秒を跨いでしまうと結果が異なりテストが失敗する。
@tyru 確認と修正をお願いできますか?

**Comment by tyru** [comment]
対応は土日になってしまうかもしれませんが、了解しました。

**Comment by tyru** [comment]
mem1, mem2, mem3を削除すればいいだけだと思いますが、
自分だと遅くなってしまうかもしれないので、thincaさんやって頂いても構わないです…すみません。

**Comment by thinca** [comment]
ずっと昔から埋まってたバグなので、遅くなっても問題ないです！(とは言え気が向いたらやるかもです)

**Comment by tyru** [comment]
すみません、再現が面倒で確認せず修正しちゃいました…レビューして大丈夫そうだったら閉じてもらっていいですか。(アッ、masterに…orz)

**Comment by thinca** [comment]
@tyru ++

**Comment by tyru** [comment]
:smile:
