### ISSUE TITLE
Web.URI で相対 URI を扱いたい

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#364]
とある html に書かれた相対パスを辿った先の URI を知りたい事例があり、`Web.URI` で相対 URI が扱えると便利かと思いました。
URI のオブジェクトとして絶対 URI と相対 URI の 2 パターンを生成できるようにして、base URI(絶対URI) に対して相対 URI (こちらは html に書かれている都合上絶対 URI の場合もありえる)を渡すと、参照先の絶対 URI が取れれば用件として十分かと思います(渡されたのが絶対 URI ならそれをそのまま返せば OK)。
そのうち実装しようかとは思ってますが、設計周りをメンテナの @tyru さんと相談したいです。(もしくはやってくれても…なんて…)

**Comment by tyru** [comment]
> URI のオブジェクトとして絶対 URI と相対 URI の 2 パターンを生成できるようにして、base URI(絶対URI) に対して相対 URI (こちらは html に書かれている都合上絶対 URI の場合もありえる)を渡す

相対URIのオブジェクトを生成するのではなくて、現在の絶対URIしか受け付けないオブジェクトにメソッドを生やして

```viml
let base_uri = 'http://example.com/foo/bar'
let rel_uri = '../baz'
let uri = s:URI.new_relative(base_uri, rel_uri)
echo uri.to_string()
" => http://example.com/foo/baz

" もしくは
let uri = s:URI.new(base_uri)
let uri = s:URI.relative(rel_uri)
echo uri.to_string()
```

のように参照先の絶対URIを取得できるようにするのはどうでしょうか？
（相対URIに対してわざわざオブジェクトを生成するのもどうかな、と思ったので）

**Comment by thinca** [comment]
なるほど、インスタンスを生成しないのでも良さそうです。
どちらにしても、引数として絶対URIと相対URIどちらも受け取れるようになっていると嬉しいです。

**Comment by tyru** [comment]
@thinca さんはどちらのインターフェースが良いでしょうか？
それとも両方あった方が良いですか？

```viml
let uri = s:URI.new_relative(base_uri, rel_uri)
```

```viml
let uri = s:URI.relative(rel_uri)
echo uri.to_string()
```

**Comment by thinca** [comment]
後者は `base_uri` がないですが、どうやって使うのでしょう?

**Comment by tyru** [comment]
あ、すみません。`s:URI`じゃなくて`uri`でした。


```viml
let uri = s:URI.new(base_uri)
let uri = uri.relative(rel_uri)
echo uri.to_string()
```

**Comment by thinca** [comment]
メソッドの方で良さそう。

**Comment by tyru** [comment]
拝承 :muscle:

**Comment by tyru** [comment]
ううむ…今までのメソッドと合わせて `uri.relative({str})` は破壊的なメソッド(=コピーを返すのではなく`uri`自身を書き換える)とします。
(今後の課題として`uri.clone()`も用意した方がいいな…今すぐ必要だったら言ってください)

#### Before

```viml
let uri = s:URI.new(base_uri)
let uri = uri.relative(rel_uri)
echo uri.to_string()
```

#### After

```viml
let uri = s:URI.new(base_uri)
call uri.relative(rel_uri)
echo uri.to_string()
```

**Comment by thinca** [comment]
今までのメソッドって各部品を上書きする奴ですよね。あれらは setter ですし、合わせる必要もないかと思いますが、どうでしょう?

**Comment by tyru** [comment]
うーん自分としてはこれらも引数を元に自分自身を書き換える意味でsetterの感覚でいました。
なので自分としては破壊的にはしたいですね…
どうしても元のuriに変更を加えたくなければ`clone()`を呼ぶ感じで。
ちなみに以下の例だとrelative()がselfを返してますが、他のsetterでselfを返すのは今後やる予定です。メソッドチェーンできるように。

```viml
let uri = s:URI.new(base_uri)
let copyuri = uri.clone().relative(rel_uri)
echo copyuri.to_string()
```

**Comment by thinca** [comment]
`clone()` があるなら破壊的でも良いです！

**Comment by tyru** [comment]
拝承  :boom: :muscle: :relieved: :+1:

**Comment by tyru** [comment]
### TODO

- [ ] URI.relative()の実装
- [ ] URI.clone()の実装

URIオブジェクトのsetterでselfを返すようにする…のは別件でいいか。
(他にも大項目だけでTODOが6件あって、これいちいちPR出すの面倒だな…
レビューしてもらうのも申し訳ないし、まとめて出しちゃおうかな…)

**Comment by thinca** [comment]
まとめてで(私は)大丈夫です！
相対 URI の実装地味に面倒だとは思いますがよろしくお願いします :bow:

**Comment by tyru** [comment]
了解です！
上のTODOはなるべく早めに別ブランチで実装するので欲しい時はいつでも言ってください！
その時は折を見てmasterにマージするので。

**Comment by tyru** [comment]
とりあえず実装しましたが、コミットメッセージの規約が気になってます。
push -fはしたくないので、pushする前に @thinca さんにここで質問しちゃっていいでしょうか。

まず、(@thincaさんには言ったと思いますが記録のために書いておくと)正規化の処理の実装のためにhttpスキーマならWeb.URI.HTTPといった様に、別モジュールとして正規化の初理を実装しました。
現在httpとhttpsのみ実装しました。

そこで気になってるのが

* Web.URI.HTTPを追加したコミットがWeb.URIも変更してるんですが、コミットメッセージは `Web.URI, Web.URI.HTTP: ...` と書けばいいですか？
  * 現状は `Web.URI: Support "http" scheme` のように書いて、モジュールを追加したものの、Web.URIのコミットとして書いてます。


### 過去ログ

http://lingr.com/room/vim/archives/2015/12/31#message-22891670

**Comment by tyru** [comment]
[Lingrでコミットメッセージの規約については現状でいいと返事をもらった](http://lingr.com/room/vim/archives/2015/12/31#message-22892357)ので、とりあえずweb/uri/implement-todoブランチにpushしました。
まだ残課題あるのでPRは出してないです。

**Comment by thinca** [comment]
実はこれもう done っぽい。

**Comment by tyru** [comment]
ありがとうございます！
