### ISSUE TITLE
Reference to external vital modules

### ISSUE THREAD

**Issue by tyru** [vim-jp/vital.vim#367]
Where should we write this? (Wiki, README.md, ...)

I found the followings (alphabetical order).
Some of the modules are deprecated.
Need filtering though.

- [x] https://github.com/daisuzu/vital-smtp
- [x] ~~https://github.com/haya14busa/vital-power-assert~~ already added
- [x] ~~https://github.com/haya14busa/vital-string-interpolation~~ already added
- [x] ~~https://github.com/haya14busa/vital-snoop.vim~~
  - deprecated
- [ ] https://github.com/haya14busa/vital-exe-assert
- [ ] https://github.com/haya14busa/vital-projectfinder
  - No doc, project description
- [ ] https://github.com/haya14busa/vital-string-converter
  - No doc, project description
- [ ] https://github.com/haya14busa/vital-vimlcompiler
  - No doc, project description
- [x] ~~https://github.com/lambdalisue/vital-VCS-Git~~ already added
- [x] ~~https://github.com/lambdalisue/vital-Web-API-GitHub~~ already added
- [x] ~~https://github.com/lambdalisue/vital-ArgumentParser~~ already added
- [x] https://github.com/lambdalisue/vital-System-Cache-File
- [x] https://github.com/lambdalisue/vital-System-Cache-Simple
- [x] https://github.com/lambdalisue/vital-System-Cache-Unified
- [x] https://github.com/lambdalisue/vital-Text-INI
- [x] ~~https://github.com/lambdalisue/vital-Vim-Guard~~
  - deprecated
- [x] https://github.com/rhysd/vital-color-echo
- [x] https://github.com/syngan/vital-regdict
- No acknowledgement yet
  - [x] ~~https://github.com/osyo-manga/vital-over~~ already added
  - [x] ~~https://github.com/osyo-manga/vital-unlocker~~ already added
  - [x] ~~https://github.com/osyo-manga/vital-reunions~~ already added
  - [ ] https://github.com/osyo-manga/vital-coaster
  - [ ] https://github.com/osyo-manga/vital-gift
  - [ ] https://github.com/osyo-manga/vital-migemo
  - [ ] https://github.com/osyo-manga/vital-palette
  - [ ] https://github.com/osyo-manga/vital-paradise
  - [ ] https://github.com/osyo-manga/vital-reti
  - [ ] https://github.com/kamichidu/vim-vital-cache
  - [ ] https://github.com/kamichidu/vim-vital-layout
  - [ ] https://github.com/kamichidu/vim-vital-pubsub
- [x] ~~Note about the licenses of each external vital module too.~~
  - This is written in each repository.

**Comment by tyru** [comment]
Added.

* https://github.com/kamichidu/vim-vital-layout
* https://github.com/lambdalisue/vital-ArgumentParser
* https://github.com/syngan/vital-regdict
* https://github.com/kamichidu/vim-vital-pubsub
* https://github.com/lambdalisue/vital-Text-INI
* https://github.com/lambdalisue/vital-System-Cache-Unified
* https://github.com/rhysd/vital-color-echo
* https://github.com/lambdalisue/vital-System-Cache-Simple
* https://github.com/lambdalisue/vital-VCS-Git
* https://github.com/kamichidu/vim-vital-cache
* https://github.com/lambdalisue/vital-System-Cache-File
* https://github.com/lambdalisue/vital-Vim-Guard
* https://github.com/lambdalisue/vital-Web-API-GitHub

**Comment by crazymaster** [comment]
It is here.
https://github.com/vim-jp/vital.vim/wiki/External-vital-modules

**Comment by tyru** [comment]
@crazymaster Thanks!
I'll merge them... but should I confirm the authors to agree with writing to Wiki?

May I write about your vital modules to Wiki?
@daisuzu @haya14busa @kamichidu @lambdalisue @osyo-manga @rhysd @syngan

**Comment by daisuzu** [comment]
No problem! :ok_hand:

**Comment by rhysd** [comment]
はい，全然問題ないです

**Comment by syngan** [comment]
問題ありません。

**Comment by haya14busa** [comment]
okです :+1:

このissueとは直接関係ないですが，(内部含めて?)外部vitalライブラリの書き方が公式でドキュメント化されてないという問題，外部モジュールがまとまっていないという問題以上にもったいない気がするので特に何か問題なければissue作って書くと便利そう(余裕があれば土台のドキュメントのPRとか出せればいいんですが保留力)

**Comment by lambdalisue** [comment]
構いません。

あと +1 to @haya14busa

**Comment by daisuzu** [comment]
http://daisuzu.hatenablog.com/entry/2014/12/07/000102
3分クッキングみたいになってますが土台の参考になれば

**Comment by thinca** [comment]
> 外部vitalライブラリの書き方が公式でドキュメント化されてないという問題

これなんですが、延び延びになってしまっているんですが、近々 #137 に対応したいと考えていて、その際に互換性のある形で作り方を変えようかと思っています。ドキュメントはその際にでも一緒に作ってしまいたい…。

**Comment by tyru** [comment]
ping @kamichidu @osyo-manga

**Comment by tyru** [comment]
We should note about the licenses of each external vital module.

**Comment by tyru** [comment]
> We should note about the licenses of each external vital module.

This is written in each repository.

**Comment by tyru** [comment]
@haya14busa
[vital-exe-assert](https://github.com/haya14busa/vital-exe-assert) は vital-power-assert が後継プラグインぽかったので載せなかったのと、あとそれ以外のプラグインも説明文が README.md、プロジェクトページ、help に見当たらなかったので載せませんでした。
もし載せてほしいのであれば一行説明文がほしいですが、まぁ面倒だと思うので別にいいのであれば無視っちゃって構わないですー。

**Comment by tyru** [comment]
ping @kamichidu @osyo-manga
↑のコメントの、載せてもいいかどうかの返事がほしいです。

**Comment by tyru** [comment]
@haya14busa 

> もし載せてほしいのであれば一行説明文がほしいですが、まぁ面倒だと思うので別にいいのであれば~~無視っちゃって構わないですー。

すみません、やっぱり issue 閉じれないので、載せるか載せないかだけ返事がほしいです。面倒だったら載せない、で全然構わないです。

**Comment by tyru** [comment]
> このissueとは直接関係ないですが，(内部含めて?)外部vitalライブラリの書き方が公式でドキュメント化されてないという問題，外部モジュールがまとまっていないという問題以上にもったいない気がするので特に何か問題なければissue作って書くと便利そう(余裕があれば土台のドキュメントのPRとか出せればいいんですが保留力)

ref. #400

**Comment by haya14busa** [comment]
んー勝手に載せていただく分にはいいんですが，載せたいという積極的な気持ちはないので説明ないやつについては載せなくていいです．

また，このissue作られたときからまた新しくいくつか多分vital module は作っているんですが，そういうの今後もメンテしていくの大変そう．

Wiki 形式にして勝手に作者が載せる形式とか，awesome-vital-modulesみたいな感じで有志が，特に作者の許可を必ずしも得なくていい形で，まとめていく形式のほうが面倒がなくてよさそうかなと感じました．

**Comment by tyru** [comment]
ですね。
正にそんな感じの事を当時この issue を立てた自分に対して思ったので、全面的に同意です。

**Comment by tyru** [comment]
> ですね。
> 正にそんな感じの事を当時この issue を立てた自分に対して思ったので、全面的に同意です。

なので、閉じちゃっても良さそう（@kamichidu さん @osyo-manga さんにわざわざ mention までしてしまったけど…）。

wiki には結構追加したし、少し待って特に反論なければ閉じます（週末くらい？）。

**Comment by rhysd** [comment]
README に [wiki](https://github.com/vim-jp/vital.vim/wiki/External-vital-modules) へのリンクがあると良い気がします．あとリンク載せるだけであれば別に持ち主の許可要らないと思います．

**Comment by tyru** [comment]
@rhysd #478 こんな感じでどうでしょうか。

**Comment by tyru** [comment]
> wiki には結構追加したし、少し待って特に反論なければ閉じます（週末くらい？）。

予告通り閉じます。
