### ISSUE TITLE
Can not read the installing file: 0

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/vital.vim#389]
`:Vitalize .` をして、更新をしようとすると発生するようになりました。
自分の中にしか存在しないファイル（`StringExt.vim`）を読みに行こうとして死んでいるようです。

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
vitalizer: Can not read the installing file: 0, after autoload/vital/_vim_gita/Data/StringExt.vim, vital_dir: /Users/alisue/.ghq/github.com/lambdalisue/vital.vim
```

ちなみに上記メッセージは下記のように修正して見えるようにしています。

```vim
      if !filereadable(from)
        throw printf('vitalizer: Can not read the installing file: %s, after %s, vital_dir: %s', from, after, g:vitalizer#vital_dir)
      endif
```
https://github.com/vim-jp/vital.vim/blob/master/autoload/vitalizer.vim#L385-L387

**Comment by lambdalisue** [comment]
ちなみに `__latest__` からコピーされたものが `_vim_gita` に入っている際に上記が発生します。コピーを消すとアップデートできるようになります。

**Comment by lambdalisue** [comment]
んー　全部がコピーされるわけじゃないっぽい。

- `Git`
- `Git.Process`
- `Data.StringExt`

の３つだけっぽい？手動で削除しましたが　https://github.com/lambdalisue/vim-gita/tree/alpha-3　です。ちなみに haya14busa さんの修正前から同様の現象が発生していました（かなり色濃いリファクタリング中だったので Vital のせいか不明だったので報告はしていませんでしたが）

**Comment by lambdalisue** [comment]
あれ、消してもだめになった・・・不明

**Comment by haya14busa** [comment]
@lamdalisue さんのエラーは再現しなかったんですが，`:Vitalize .`すると自分が持っってるモジュールが`_vim_gita`に入ってしまう問題は再現しました．
これ，おそらくなんですが`_vital_depends`で依存されている場合はコピーしてしまうというのが問題ですね．

**Comment by thinca** [comment]
`_vital_depends` で自分が持ってるモジュールを指定していると起きますね…。なんとかします。

**Comment by thinca** [comment]
#389 で直ったはず。
