### ISSUE TITLE
RFC: Process に関する質問

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/vital.vim#394]
Process では内部にて `iconv` を利用して [inputの変換](https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__latest__/Process.vim#L102) および [outputの変換](https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__latest__/Process.vim#L143) を行っているのですが、これは必要な処理なのでしょうか？

といいますのも vim-gita にて `git show HEAD:sjis.txt` のようなコマンドを走らせて、出力結果を `Vim.Buffer.edit_content()` で読む処理を書いていたのですが `output` の変換処理により一時ファイルに sjis を無理やり `&encoding` に変換したものが書き込まれていたため、期待するコンテンツと変わってしまっていました。

個人的には INPUT/OUTPUT の調整は開発者側で行うことであってライブラリでは与えられたもの、得られたものをそのまま渡すほうが良いかと思います（`s:need_trans` 関連は必要そうですが）。

あと `spawn` の場合、`vimproc#system` の場合および `system` の場合で `shellescape` 関連の処理が大幅に違うようですが、なぜこうなるのかちょっと良くわかりませんでした。

https://github.com/vim-jp/vital.vim/blob/7b00ba689ff482b0b1470727b4cadb3f1f43c6de/autoload/vital/__latest__/Process.vim#L126
https://github.com/vim-jp/vital.vim/blob/7b00ba689ff482b0b1470727b4cadb3f1f43c6de/autoload/vital/__latest__/Process.vim#L33
https://github.com/vim-jp/vital.vim/blob/7b00ba689ff482b0b1470727b4cadb3f1f43c6de/autoload/vital/__latest__/Process.vim#L38

この辺りの経緯をお聞きしたいのですが、いかがでしょう？ ? @tyru

**Comment by lambdalisue** [comment]
ちなみに vim-gita では `Vim.Process` という感じでもう少し row level のものを作って利用しました。
https://github.com/lambdalisue/vim-gita/commit/7eb98ded8d001a2c4cfc9a0f48852ac822cd3bdb

エンコード関係や `shellescape` の部分など経緯がよくわからないところはシンプルな感じに修正してしまっているので、上述したような処理が必要になった経緯をお聞きしたいなという感じです。

**Comment by tyru** [comment]
> 個人的には INPUT/OUTPUT の調整は開発者側で行うことであってライブラリでは与えられたもの、得られたものをそのまま渡すほうが良いかと思います（`s:need_trans` 関連は必要そうですが）。

:+1: 
敬意については詳しくは #169 を参照してください。

> あと `spawn` の場合、`vimproc#system` の場合および `system` の場合で `shellescape` 関連の処理が大幅に違うようですが、なぜこうなるのかちょっと良くわかりませんでした。

引数の処理の仕方が違うからです。

**Comment by lambdalisue** [comment]
#169 的に `s:need_trans` は必須で他のエンコーディングはおもてなしっぽいですね。了解です

> 引数の処理の仕方が違うからです。

なるほ・・・ど？ Windows の `shellescape` って `\` エスケープしてくれないとかで辛いから自前で置き換えという感じでしょうか

**Comment by tyru** [comment]
\# 本文のURL 3つをHEADじゃないURLに置き換えちゃいました。

> なるほ・・・ど？ Windows の `shellescape` って `\` エスケープしてくれないとかで辛いから自前で置き換えという感じでしょうか

あれ？すみません、 `s:spawn()` と `s:system()` どっちの話をしてますか？
もし `s:system()` の話なら、`shellescape()`は直接呼んで`shellslash`を一時的に変えてます (これもどうかと思いますが)。
むしろvimprocに対する対応で、vimproc parserが自前でコマンドライン引数をパースするので、`system()`と同じ渡し方ではまずくて今の `s:system()` の実装になったと記憶してます。

**Comment by lambdalisue** [comment]
```
> tyru

Process の話なんですが

s:system() だと自前 s:shellescape 呼んでませんか？

https://github.com/vim-jp/vital.vim/blob/7b00ba689ff482b0b1470727b4cadb3f1f43c6de/autoload/vital/__latest__/Process.vim#L126
2 minutes ago
(〃`l _ l´)つ意味

vital.vim/Process.vim at 7b00ba689ff482b0b1470727b4cadb3f1f43c6de · vim-jp/vital.vim · GitHub
2 minutes ago
Λlisue

で、その自前が https://github.com/vim-jp/vital.vim/blob/7b00ba689ff482b0b1470727b4cadb3f1f43c6de/autoload/vital/__latest__/Process.vim#L153
2 minutes ago
(〃`l _ l´)つ意味

vital.vim/Process.vim at 7b00ba689ff482b0b1470727b4cadb3f1f43c6de · vim-jp/vital.vim · GitHub
2 minutes ago
Λlisue

で結構頑張ってる感あるんですが、なんでだろうなーと
2 minutes ago
thinca

command! -nargs=+ Set (execute has('vim_starting') ? 'set' : 'setglobal') <q-args>

こ、こうかな?
1 minute ago
Λlisue

つらそう・・・
1 minute ago
thinca

Set 実行毎に条件分岐するのもアレだから、やるならコマンド定義時に分岐した方がいいな
now
tyru

thinca: ですね…

ryunix is now offline
now
tyru

Alisue: あ、ほんとだ… 自前 s:shellescape() 使ってますね。

あとできればissuesの方で会話ログ残してほしいです。参照リンク貼ったり見に行くのも面倒だと思うので
now
Λlisue

ぉ、OKです。そっちに移ります
```

**Comment by lambdalisue** [comment]
この自前 `s:shellescape()` の理由がわからなかったので怖い感じです。

**Comment by tyru** [comment]
引用ありがとうございます！

> この自前 s:shellescape() の理由がわからなかったので怖い感じです。

正直自分も Process の今の実装に関して色んなプラグイン (主に open-browser.vim) で使って今の実装になった感じなので、テストがちゃんと書かれた Process の実装があれば良いとは感じてます…

とりあえず `iconv()` での変換に関しては変換しない方が良い場面もあると思うので、
@lambdalisue さんのモチベーションがあれば `a:1 = {dict}` に `"notrans"` みたいなキーを追加してもらっても構いません。
(@lambdalisue さんは既に別実装使ってるようですが)

**Comment by lambdalisue** [comment]
> 正直自分も Process の今の実装に関して色んなプラグイン (主に open-browser.vim) で使って今の実装になった感じなので、テストがちゃんと書かれた Process の実装があれば良いとは感じてます…

wktk

> とりあえず iconv() での変換に関しては変換しない方が良い場面もあると思うので、
@lambdalisue さんのモチベーションがあれば a:1 = {dict} に "notrans" みたいなキーを追加してもらっても構いません。

そうですね、こちらは現在の使用感と変えるわけにも行かないと思うので `encode_input`, `encode_output` オプションを用意してデフォルトで `1` にする的なのがいいかなと思います。そのうちやりますね。

**Comment by tyru** [comment]
@lambdalisue ありがとうございます！

**Comment by lambdalisue** [comment]
#397

**Comment by tyru** [comment]
:+1:
