### ISSUE TITLE
Stop to use files.kaoriya.net to download vim

### ISSUE THREAD

**Issue by koron** [vim-jp/vital.vim#416]
Could you stop to use files.kaoriya.net to download vim.
You can use releases in koron/vim-kaoriya instead of it.

cf. https://github.com/thinca/vim-themis/pull/32/files

**Comment by crazymaster** [comment]
Work In Progress
https://github.com/vim-jp/vital.vim/pull/408

**Comment by crazymaster** [comment]
今のoldestのバイナリだとif_pythonに問題(see #408)があるようなので、
vim73-kaoriya-win64-20110306.zip辺りに差し替えてもらったほうがいいかも

**Comment by crazymaster** [comment]
もしくはUbuntu 12.04に合わせて7.3.429前後というのもあり？

**Comment by crazymaster** [comment]
@koron ping

**Comment by koron** [comment]
oldest の差し替えはしないです。

追加はしても良いですが、幾つかの理由で乗り気ではありません。

*   Ubuntu のために Win で 7.3 でテストするのは、スジが通らない。Ubuntu を使ってテストすべき
    *   次のLTSが控えていて 7.4 になるので、なおのこと Win で労力を割きたくない
*   適切な名前/理由が思いつかない

**Comment by koron** [comment]
> if_pythonに問題

あとは、この詳細書いてもらえませんか? 408にも詳細な情報は見当たらなかったので。
それ次第では考えなおしもあります。

**Comment by crazymaster** [comment]
今のoldestのバイナリ(vim73-kaoriya-win64-20110227.zip)だとif_pythonでクラッシュします
vim73-kaoriya-win64-20110306.zipだと問題ないです

**Comment by koron** [comment]
使ってるPythonのバージョンはなんですか?
手元で動かしても、必ずクラッシュしますか?

なお 20110306 では 2.7 に切り替わっていますね。

**Comment by crazymaster** [comment]
pythonはvimのコンパイルオプションに合わせて2.6にしてあります
ローカル環境では未検証です

**Comment by koron** [comment]
とりあえず手元のローカル環境で 20110306 + 2.6.6 (64bit版) で以下を実行したところ、正常に実行できました。

    :py import sys; print(sys.version)

vital.vim が利用している Python のコードに 2.6 へ対応できていないものがあるか、
なにかしらのバグがあるか、秘孔を突いているかのどれかでしょう。

なので、これをもって考えなおす、配布物の差し替えを行なうことはありえません。

**Comment by crazymaster** [comment]
> とりあえず手元のローカル環境で 20110306 + 2.6.6 (64bit版) で以下を実行したところ、正常に実行できました。

えっと、落ちるのは 20110227 版です

**Comment by koron** [comment]
> えっと、落ちるのは 20110227 版です

既に修正済みですが、書き間違えです。

**Comment by koron** [comment]
追記分を再記入

---

oldest でのテストを諦めるか、
vital.vimのコードを修正するか、
もしくはピンポイントで上記バイナリが落ちる原因を示すか、
そんな感じで vital.vim のほうで対応してもらえませんか?

**Comment by koron** [comment]
たぶんコイツ https://github.com/vim-jp/vital.vim/blob/master/test/Vim/Python.vimspec が 2.6 で動かないのとちゃう?

**Comment by k-takata** [comment]
vimprocもこの対応しないといけないのか。
.bat からappveyorコマンドでダウンロードしてるのどう直せばいいのかな。

**Comment by koron** [comment]
@k-takata 向こうにissueたててもらえます?

**Comment by k-takata** [comment]
PRお待ちしています。 :smiley:

**Comment by crazymaster** [comment]
> Ubuntu のために Win で 7.3 でテストするのは、スジが通らない。Ubuntu を使ってテストすべき

ubuntuでは12.04がサポート期間が残っているのでとりあえず現状維持（7.3.429）で良いと思いますが、windowsではfinal(7.3.1314)に上げてしまってもいいかもしれませんね

調査してもらっておいて申し訳ないですが...

**Comment by crazymaster** [comment]
fixed in #429
