### ISSUE TITLE
vital#plugin_name#of() の関数名について

### ISSUE THREAD

**Issue by tyru** [vim-jp/vital.vim#431]
#415 でもちらっと言われてましたが、`vital#plugin_name#of()` という関数名は自分も正直微妙だと感じています。
`of()` という関数名/メソッド名は例えば [Java の Optional クラスのように引数を取るメソッド](https://docs.oracle.com/javase/jp/8/docs/api/java/util/Optional.html#of-T-)の場合なら自然だと思います。
なぜなら `vital#myplugin#of("value")` なら英語の語順にマッチしているため、
`"value"` という値からオブジェクトを生成するファクトリーメソッドなんだな、と理解できるからです。
なので自分としてはあくまで例ですが以下のような関数名が適切かと思います。

* `vital#myplugin#new()`
* `vital#myplugin#get()`

後出しジャンケンなのは承知しているので、もし議論した上で変更するとなったら私に assign してもらって構いません。

# 関数名の案

それぞれの案に賛成している人も記載してます。
(もし違ってたら編集しください)
※関数名はアルファベット順

* `vital#{plugin-name}#new()`
  * @haya14busa, @ujihisa, @lambdalisue, @tyru
* `vital#{plugin-name}#loader()`
* `vital#{plugin-name}#get()`
* `vital#{plugin-name}#of()` を消して `vital#{plugin-name}#import()` を直接呼んでもらう

**Comment by tyru** [comment]
またここでの議論を元に以下のタスクを行う予定です。

* ドキュメントの更新 (#432)
* 関数名の変更 (必要であれば)

**Comment by lambdalisue** [comment]
Lingr で ujihisa さんも指摘していましたが new/get だと「新規作成／既存の取得」の意味が強いので、現在の「キャッシュが存在していない場合は作成、存在していれば取得」が少し辛そうです。

`vital#myplugin#instance()`

などはどうでしょうか？

**Comment by lambdalisue** [comment]
> みなさん何か勘違いしているようですが vital#of() は常に新しいオブジェクトを作成します

http://lingr.com/room/vim/archives/2016/05/02#message-23248358

vital#myplugin#new() で決定でいいかとｗ

**Comment by tyru** [comment]
Lingr より引用。

http://lingr.com/room/vim/archives/2016/05/01#message-23248190

> @ujihisa: of()のニュアンスは、あるならそれを取得、ないなら作る、みたいなやつなので

このニュアンスは自分にはありませんでした。
ファクトリーメソッドにする理由はいわゆる Flyweight パターンなどを実装するためでもありますが、それはあくまでそういうパターンが多いというだけで如何様にも実装を変える事ができる (例えば Flyweight パターンのようにキャッシュしたりなど) 事がコンストラクタではなくファクトリーメソッドにする意味かなと思っています。
自分としてはあくまで**メソッド名が英語の語順と違うので違和感がある**、と述べたつもりてす。

> @thinca: みなさん何か勘違いしているようですが vital#of() は常に新しいオブジェクトを作成します

はい、その認識です。

**Comment by tyru** [comment]
@lambdalisue なるほど。new() 派ですね。
new() が無難なので自分も同意見なのですが… なんか他にも良さそうなメソッド名があれば聞きたい所です！

**Comment by ujihisa** [comment]
`(///`

というわけでnew++

**Comment by tyru** [comment]
Lingr で @haya14busa さんからいっそ of() でローダーオブジェクトを生成せず、そのまま `vital#{plugin-name}#import()` を呼ぶ方が速いので良いという意見がありました。
なので選択肢として **vital#{plugin-name}#of() 関数を消す** というのも冒頭のコメントに追加しました。

**Comment by tyru** [comment]
そしてさらにその後の Lingr の話し合いでやはり of() 相当の関数は必要なので new() が良いという案が @haya14busa さんから出ました。
自分のこの案に納得したので自分も今では new() 派です。

> vital#of 相当を残さないと既存のvitalユーザにvital#of変えてくれと言うのはめんどくさくなるだろうし，やはり#of か#new は欲しいな
> というかそもそも.search()とか.exists()とかもあるし
> ｵｽｽﾒするのは#importだとしても，いままでのof相当が欲しい
> vital_loaded(V)のVはいままでのローダーオブジェクトなので，それと同じものを取得できるやつはあってもよいかなぁと
> http://lingr.com/room/vim/archives/2016/05/02#message-23249245

**Comment by tyru** [comment]
冒頭のコメントに皆さん自分の名前入れて投票してほしいです！

**Comment by tyru** [comment]
一応この issue の期限はGWの最終日前日までで良いかなーと考えてます。
それを過ぎるなら放置するだろうと思われるので、最終日に `vital#myplugin#new()` への書き換えと #432 をやっちゃいます。

**Comment by haya14busa** [comment]
変えるなら早めにやってもいいんじゃないかと思います．最近新しく入ったAPIをリネームしてしまうわけですから，早いほうが影響は少ないはずです．
いまの help には vital#of が deprecated で vital#{plugin-name}#of を使えと推奨してしまっています．

一旦そちらに変えたひとにもう一度変えてもらうというのはなるべく少ないしたいです．
new に変える以外の方向性はもうなさそうですし．

ひとつ他に選択肢があるとすればそのまま変えないくらいでしょうか．
まぁ僕がPRしてたことからも分かるとおり?，個人的にはいままでの`vital#of` を考えたら `vital#{plugin-name}#of`でええんちゃうか，不必要にAPI変えなくてもいいんじゃないかと思ってたりします．

ネイティブでもないし，`of`はvitalくらいでしか見たことなかったので，ofの違和感というのがどこまでのものかは結局測りかねてますが．
(語順がオカシイのはわかりますが，用法が仮にあってるなら仕方ないのではという気持ちがある)

**Comment by haya14busa** [comment]
一応 `of` 残し :dog: チャンあるのではという補足．ofあんまりわかってないけど．

> ujihisa: of()のニュアンスは、あるならそれを取得、ないなら作る、みたいなやつなので
> thinca: みなさん何か勘違いしているようですが vital#of() は常に新しいオブジェクトを作成します

この常に新しいオブジェクトを作成するというのは以前からです．
ということは `あるならそれを取得、ないなら作る` というのはインスタンスが新しいかというよりは，
ある１つのプラグインのローダが`あるならそれを取得、ないなら作る`というニュアンスに近いのかなと思いました．

ローダーは1つのプラグインに1つで十分で，いくつローダーのインスタンスを作ろうが同じことしかやりませんしできません．(`Vital-Vital.load()` の存在を抜きにして考えれば)

まぁ `.load()` という例外が存在してるのでｱﾚですが，当初のujihisaさんがいうニュアンスはこちらの意味なのではないでしょうか．
実際 (`load()` を考えなければ)，内部の実装で1つのインスタンスを返すというふうに変更しても問題ないです．`.load()`含めても1つのプラグインには1つのローダのみという仕様にしてしませばそこまで違和感ないのではと思います．

```
let V1 = vital#vital#new()
let V2 = vital#vital#new()
```

`new` はなんとなく`V1`と`V2`が別物という印象を受けますが実際やることは一緒なので違和感があるように思えてきました．

なんか早く決めろといったそばから議論を蒸し返すようで申し訳ないです... :bow:

個人的に互換性崩す変更はなるべく避けて必要最低限にしたい...というバイアスもあると思います．
みんな new 推しが多いし間違ってる気もしますがまぁ1つの意見として

**Comment by tyru** [comment]
> ということは `あるならそれを取得、ないなら作る` というのはインスタンスが新しいかというよりは，
> ある１つのプラグインのローダが`あるならそれを取得、ないなら作る`というニュアンスに近いのかなと思いました．
> 
> `new` はなんとなく`V1`と`V2`が別物という印象を受けますが実際やることは一緒なので違和感があるように思えてきました．

なるほど。インスタンス云々の違いより役割的な話ですね。
それで言うと、これまで出てる案で一番ニュアンス的に合ってるのは `vital#{plugin-name}#get()` のような気がしてきました。
ただ get は汎用的な言葉すぎる気がするので、具体的には `vital#{plugin-name}#loader()` とかが良いかもしれません。
`vital#myplugin#loader()` みたいな感じで語順的にも違和感がないような気がします。

ただ of() に関しては、似たメソッドとして from() 等がありますが、やはり引数に何かを受け取ってそれを元に変換してインスタンスを生成するメソッドという意味合いが強い印象があります (個人的な印象ですが)。
なので私としては of() には否定的な立場です。
http://blog.kengo-toda.jp/entry/2015/07/15/022040
http://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6#comment-ea37f3a92fff4e620e28

**Comment by tyru** [comment]
`vital#{plugin-name}#loader()` を冒頭のコメントに追加＆投票しました。

**Comment by haya14busa** [comment]
loader は主な役割がローダーというだけで，`plugin_name()`とか微妙にローダーの役割か...?というものが混ざっているのでつらい．今後追加したくなるかもしれないし

**Comment by haya14busa** [comment]
> それで言うと、これまで出てる案で一番ニュアンス的に合ってるのは vital#{plugin-name}#get() のような気がしてきました。
ただ get は汎用的な言葉すぎる気がするので、

get がいいような気がしてきた．もともとほとんど意味のない名前のメソッドを探していたというのもあるし，なかったらエラーになるというニュアンスだと言っていた気もするけど，getの使われ方的にその限りではない気がする．

**Comment by haya14busa** [comment]
だめだ早く変更したほうがいいんじゃないかという当初の目的がブレてる...getとかにするくらいならnewでいいかな

**Comment by ujihisa** [comment]
> だめだ早く変更したほうがいいんじゃないかという当初の目的がブレてる...getとかにするくらいならnewでいいかな

`vital#{plugin-name}#vital()` という案も提案してみる (さらにかき回す悪質なコメント)

メリットとして、`vital#vital#vital()`ができるようになります。

---

こちらとしては`{new(), get()}++` で`of()--`です!

**Comment by tyru** [comment]
API の変更なら慎重にやるべきだし、議論が活発化してるなら尚更待ってみてもいいんじゃないかとは思います >早めに変更

**Comment by tyru** [comment]
こうなるといっそ中二感溢れる名前にしたくなってきました…！
power とか catalyst とか vivify とか

**Comment by ujihisa** [comment]
> こうなるといっそ中二感溢れる名前にしたくなってきました…！(さらにかき回すコメント)

このために関数名に絵文字を使えるよう Vim本体にパッチを投げるフラグ

**Comment by tyru** [comment]
let :heart: = vital#myplugin#:heart:()

**Comment by haya14busa** [comment]
new でいーんじゃないっすかね

**Comment by tyru** [comment]
しばらく返事しないですみません。
自分も new が妥当だと思いますので変えちゃいます。
投票の結果的にはとっくに new で結論出てますが、期間が開いてしまったので、今日の夜頃に始めます。

**Comment by tyru** [comment]
new に変わったので閉じます。ありがとうございました。
