### ISSUE TITLE
既存の help の vital#of('vital') を修正する

### ISSUE THREAD

**Issue by tyru** [vim-jp/vital.vim#432]
via #415

**Comment by tyru** [comment]
# 修正箇所

以下のファイルの `vital#of('{plugin-name}')` の呼び出しを `vital#{plugin-name}#of()` に変更

* doc/
* README.md

# 確認など

* [確認] `test/` 以下と `benchmark/` 以下の `vital#of()` の呼び出しはそのままですよね？ >@haya14busa

**Comment by haya14busa** [comment]
test/以下も変えたほうがいいです．

**Comment by tyru** [comment]
`vital#of('vital')` って新ローダーだとどう書けばいいんでしょうか？

**Comment by haya14busa** [comment]
`vital#vital#of()`です
