### ISSUE TITLE
ProcessManager: stderr.read() のタイムアウトについて

### ISSUE THREAD

**Issue by wonderful-panda** [vim-jp/vital.vim#442]
`ProcessManager.read_wait()`  内に以下のような処理がありますが、stderrに何も出力されていない場合、read_waitに指定したtimeout値にかかわらず必ず100ミリ秒待たされます。(Windowsの場合、 [この問題](https://github.com/Shougo/vimproc.vim/issues/261) によって最悪1.6秒近く待たされます。)

```vim
let [x, y] = [p.stdout.read(), p.stderr.read()]
```

stderrのreadについては `p.stderr.read(-1, 0)` (wait無し)とかでもよいのではないかと思うのですが、いかがでしょうか？

**Comment by ujihisa** [comment]
というわけで pullreq #443 してみました。指摘してくださったのは`stderr`についてですが、`stdout`についても同様にやってみました。これは`ConcurrentProcess`が用いている方法と同じでもあります。

**Comment by wonderful-panda** [comment]
ありがとうございます。
基本的にはConcurrentProcessを使うべきということなんですね。
