### ISSUE TITLE
Drop Vim 7.3 support

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#450]
Vim 8.0 がリリースされました。
そろそろ頃合いかと思うので、Vim 7.3 はタグなりブランチでマークしつつ HEAD からは徐々に(気付き次第) Vim 7.3 サポートを外したいと思います。
CI も 7.3 では回さない方向で。
賛成/問題ない方は :+1: お願いします。

**Comment by thinca** [comment]
こういう場合(古いバージョン向けのサポートバージョンを残したい場合)ってどういうブランチ or タグ名がいいですかね?
他の例知っている方いたら教えて頂けると助かります。(名前と、タグorブランチ)

**Comment by lambdalisue** [comment]
https://github.com/ipython-contrib/jupyter_contrib_nbextensions　とか

**Comment by thinca** [comment]
Travis(Ubuntu 12.04.5 LTS) の Vim は今だ 7.3.429 なんですね。まあ…もういいよね…。

**Comment by thinca** [comment]
とりあえず名前とかは後からどうとでもなるだろうということで [`vim-7.3-support`](https://github.com/vim-jp/vital.vim/tree/vim-7.3-support) と言うブランチを作りました。
tag の方がいいみたいな話は随時受け付ける感じとします。
CI の環境を変えないといけないんですが、それは別 Issue 立てます。
