### ISSUE TITLE
CI 環境の更新 (7.3環境で回さない)

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#451]
#450 関連。
Vim 7.3 のサポートを切ることにしたので、CI でも回さないようにしたいと思います。
個人的には以下のバージョンで回したい。

- Vim 7.4.000 (もしくはこれに近いバージョン)
- Vim 8.0.0000 (もしくはこれに近いバージョン)
- HEAD

Vim 7.4.0 と Vim 8.0.0000 なんですが、現在の CI の設定だと Linux は本家リポジトリを clone & build しているので簡単なんですが、Mac と Windows が面倒そうです。(Windows は @koron さんに協力してもらえればそんなに大変ではないかも)

**Comment by thinca** [comment]
ついでに Mac では通常 Vim と MacVim 両方で回せると良いかもと考えているけど、これは別件かなぁ。

**Comment by koron** [comment]
7.4.000が良いのです?

**Comment by thinca** [comment]
具体的なバージョンについては意見があれば欲しいところなんですが、7.3 系のサポートを落とす方針なので、ではサポートする最低バージョンはいくつかとなると 7.4.000 かなぁと言う感じです。
世の有名 Linux ディストリが標準搭載している Vim のバージョンなど、何か別の基準もアリかもしれません。

**Comment by koron** [comment]
Windows のほうは +kaoriya でよければ 20130811 がそれっぽいので、
一旦このチケットに attach しときます。

* [vim74-kaoriya-win32-20130811.zip](https://github.com/vim-jp/vital.vim/files/479747/vim74-kaoriya-win32-20130811.zip)
* [vim74-kaoriya-win64-20130811.zip](https://github.com/vim-jp/vital.vim/files/479746/vim74-kaoriya-win64-20130811.zip)

本家で配ってたやつについてはftp://ftp.vim.org/pub/vim/pc/ から持ってくればよいのかも。

* ftp://ftp.vim.org/pub/vim/pc/gvim74.exe (インストーラ)
* ftp://ftp.vim.org/pub/vim/pc/gvim74.zip (インストーラなし)
* ftp://ftp.vim.org/pub/vim/pc/gvim74-1024.exe (1024で1回リリース作ったみたい、理由は不明)

Winおそらく大丈夫だけど、Mac はもしかしたら古いバイナリが新しいOSでは動かない可能性もw

**Comment by thinca** [comment]
リンクありがとうございます！実はちょっと探したんですけど探し方が悪かったのか見当たらず… :sweat_smile: 大変助かりました！

> Mac はもしかしたら古いバイナリが新しいOSでは動かない可能性もw

ｳｯ…明日 Mac 触れるので時間があったら試してみようと思います！

**Comment by koron** [comment]
そして github 上では ftp がリンクにならないことが判明w

**Comment by k-takata** [comment]
Ubuntu 14.04はVim 7.4.54でしたっけ？
Vim 7.4の初期は新しい正規表現エンジンが安定していなかったですね。

**Comment by thinca** [comment]
> Vim 7.4の初期は新しい正規表現エンジンが安定していなかったですね。

ありましたね…。懐かしい…。

**Comment by koron** [comment]
@thinca とりあえず +kaoriya で欲しいバージョンがあったら言ってください。
そのものズバリがなければ一番近いのを出しますゆえ。

自分用メモ: https://github.com/koron/vim-kaoriya/blob/master/old/CHANGES-7.txt をみれば、バージョンとファイル名の対応が取れる。

**Comment by thinca** [comment]
@koron ありがとうございます！7.4 はさっき教えて頂いたやつで、8.0 は http://files.kaoriya.net/vim/vim80-kaoriya-win64-8.0.0000-20160912.zip これが良さそうなので、ひとまず Windows +kaoriya については問題なさそうです！
(ところで +kaoriya 版とそうでない版両方で回すべきかはちょっと難しい… too much な気もする。既存の CI 設定ではバイナリの入手容易性から +kaoriya 版でのみテストしている)

**Comment by koron** [comment]
オフシャルのリリースと https://github.com/vim/vim-win32-installer の最新版で回しておけば、一貫性は取れるんじゃないでしょうか。
+kaoriyaは +α のオマケくらいで。

**Comment by k-takata** [comment]
vim-win32-installerはOLEが有効になっているので、一発 `gvim -silent -register` を実行しておく必要がある点に注意。

**Comment by thinca** [comment]
長らく止まってしまっていて申し訳ない感じですが… :bowing_man:
現在のステータスです。
 
- [x] Windows
  - URL を教えてもらったのでそれを使えばできるはず(実際には試してないけども)
- [ ] Mac
- [x] Linux
  - CI内でビルドはすでにしているので、任意のバージョンのビルドが可能なはず(if_xxx については不明。ともあれあとで試す)

Mac のみ目処がだっていない状態で、現状は環境にそのまま用意されている Vim と brew で入れた最新の Vim で回している感じのところを任意のバージョンで回せるようにするのがゴールです。
`brew install {formula-url}` って感じのことができるとわかったので、brew 本体の履歴から Vim 7.4 の formula を探してきて、

```
brew install https://github.com/Homebrew/homebrew-core/blob/92190c13f2955bd8c1f992a79bd81a971944f0d7/Formula/vim.rb
```

としてみたんですが、うまく行きませんでした…(たぶん最新の brew に古い formula を食わせたからだと予想)

```
/Users/xxx/Library/Caches/Homebrew/Formula/vim.rb:48:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:135:in `block in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1080:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1812:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1799:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1075:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:187:in `<main>'
```

brew を使わないとなると依存の解決を自前でやらないとならず、ちょっと大変そうです。Mac については一旦 7.4 を保留して brew の最新版のみでテストすることにして、全体を先に進めようかなと考えています。

**Comment by thinca** [comment]
@koron
> Windows のほうは +kaoriya でよければ 20130811 がそれっぽいので、
> 一旦このチケットに attach しときます。

あーなるほど、これこの Issues に attach されているんですね…(ちゃんと理解してなかった)。
これ、そのまま使っても大丈夫ですかね? ちゃんとしたところに置いた方が良い?
それと redirects にきちんと登録するべきかな…。

**Comment by koron** [comment]
github がどう扱うかわからないですが、一旦このまま使ってしまうのはどうでしょう?

vim-jp/redirects へのURLの登録はあると良さそうです。
そうすればあとで置き場所変える時にも、比較的簡単に対応できますし。

懸念事項は、redirectsはクッションページの解釈が必要なことですかね。
たしかもうどこかでやった記憶があるので、大丈夫だとは思いますが。

**Comment by thinca** [comment]
ありがとうございます。

> 懸念事項は、redirectsはクッションページの解釈が必要なことですかね。
> たしかもうどこかでやった記憶があるので、大丈夫だとは思いますが。

https://github.com/vim-jp/vital.vim/blob/master/appveyor.yml#L16
これのことですよね。すでに redirects を使っているので、そこは大丈夫そうです。

**Comment by thinca** [comment]
@koron ここで報告するのはビミョウに違う気もしますが、ついでということで。
redirects に Vim 7.4 +kaoriya oldest と Vim 8.0 +kaoriya oldest (release に 8.0.0000 はなかったので正確には8.0.0003) を追加しました。
https://github.com/vim-jp/redirects/compare/f2a7cdcb7d40516bb060d6848853e0b40679288a...91ab857d7e33200e31f70f0ef286f60f30362228
何かまずい点ありましたらご連絡ください 🙇

**Comment by koron** [comment]
no problemです。

微妙ついでにいうと 7.4/finalもあったほうが良いですかねぇ?

**Comment by thinca** [comment]
7.4 は alpha/beta が切られずに開発されたので、7.4 の最終版は 8.0.0000 とほぼ大差ないんですよね…。
上記の事情もあるので、なくても困らないかなぁと思います。

**Comment by thinca** [comment]
7.3 のドロップは完了したので Close します。
別途改善(主に Mac)が必要だと思うのでそれらは別 Issue 立てます。
