### ISSUE TITLE
CI のスタイルチェック(lint)を独立させる

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#454]
現在 Travis CI 上でついでにスタイルチェック(vimlint)を行っているが、
- Travis は Matrix 機能で複数回走るがスタイルチェックは1度だけで良い
  - 現状これのために特定の環境でだけ走るようにしてはあるが、環境が増えた際などに面倒
- PR 画面からは Travis 全体の成否の結果しか見れないため、テストが落ちたのかスタイルチェックにひっかかったのかぱっと見わかりづらい

などの問題がある。
Travis 自体に1プロジェクトに対して複数タイプ(PR上で別々のstatus)のテストを回せる機能があれば良いのだけど、どうもなさそうなので、別の CI サービスを使ってスタイルチェックを行いたい。
### 懸念点
- 依存サービスが増える
  - サービスが落ちると CI に支障が出るため、そのリスクが増す
  - とは言えそう問題になることもないだろうと考えている
- 他に分離できるものは?
  - 今確認したら changelog のチェックもしていた。これもスタイルチェックに分離できそう。

**Comment by haya14busa** [comment]
ここでさっそうと  https://github.com/haya14busa/reviewdog が現れるわけですねわかります :dog:

とまぁ冗談はおいておいて， vim-vimlint の引数でチェックしないようにしているのを戻したり，vint は文字列チェックとかでfalse positive なレポート多くてせっかくはやいけどつらぃ.... みたいな話もあるとおもっていて，p-r に自動でコメントするならそういうたまにある問題も無視すればいいので導入できたりするかもなーとか思っています．

reviewdog 使うなら CI サービス機能の制約上, CircleCI or 僕がhost している OSS版 drone.io かという感じになります． 
drone.io だと安全にコメント用botのgithub token管理できるのだけど，まぁ若干安全ではないけど circle ci でやっておくと便利かと思います．

興味があれば導入やりますっ

**Comment by thinca** [comment]
実はこの Issue を建てた時点で似たようなことをやろうと思っていたので、はやぶささんには完全にしてやられた(いい意味で)と言う感じです。
というわけで現在導入を試みてあれこれやっております。できなさそうだったらお願いするかもしれません！

**Comment by haya14busa** [comment]
なるほど期待力! なにかあったらメンションしていただけると対応できる範囲で対応します!

**Comment by thinca** [comment]
別の場所で昨日やりとりしましたが、この件は @haya14busa さんに丸投げ(言い過ぎ)という形になりました。
@haya14busa 私にできることがあれば何なりと!

**Comment by haya14busa** [comment]
おそくなってスイマセン...!

やろうかとおもったら，activateにはGitHub の admin 権限が必要っぽくactivateできませんでした :sweat_drops: 
たぶん thinca さん admin 権限持っていると思うので activate していただけませんか?

web ui http://droneio.haya14busa.com/vim-jp/vital.vim

or drone.io のコマンド

```
drone repo add vim-jp/vital.vim
```

**Comment by thinca** [comment]
done!

**Comment by haya14busa** [comment]
thx!

**Comment by thinca** [comment]
#458 にて完了っ!
