### ISSUE TITLE
Please describe what vital.vim provides *with a paragraph*

### ISSUE THREAD

**Issue by umireon** [vim-jp/vital.vim#474]
**As a newbie on vital.vim**

I cannot understand what vital.vim provides and aims at.
I know [the project page](https://github.com/vim-jp/vital.vim#readme) has a *comprehensive* list of modules but I don't want to *check it out* such a long and **uninteresting** table, which is **only** repeating the same words in the same line.
In addition, [the brief description field](https://github.com/vim-jp/vital.vim#readme) and [the introduction section](#vitalvim--) gave me no information but the word *comprehensive* and the idea “Ah! RUBY and JS can be combined!”

Can you give me a description as written in the first sentence of [Boost on Wikipedia](https://en.wikipedia.org/wiki/Boost_(C%2B%2B_libraries)), which gives me a clear concept what Boost provides?

**Comment by tyru** [comment]
At the beginning of vital.vim, vital.vim is the library to just cover the poor Vim script capability.
But in Vim script, using external library brings another problems:

* Does the library place to single repository or not?
* If the answer is "Yes"
  * Updating the library is tedious
  * Checking destructing changes are super tedious
* If the answer is "No"
  * User must install it manually
  * There is no version locking system in Vim script

The above problems are only when one library depends no other libraries.
If it depends other libraries or when using multiple libraries, the problems become more complicated. 
vital.vim solves the above problems.

**Comment by umireon** [comment]
> vital.vim solves the above problems.
By what means? By concatenating the libraries on the internet into one file as [browserify](http://qiita.com/cognitom/items/4c63969b5085c90639d4) does?
If so, where is the software repository like [npm](https://www.npmjs.com/search?q=random)?

**Comment by tyru** [comment]
vital.vim solves the problems by:

* vital.vim **embed** libraries into developer's repository so user doesn't have to install manually, and also there is no need to care about a version of libraries.
* Vital "modules" can depend other "modules".
* When embedding modules, vital resolves the dependencies and install only necessary modules.
* If there are already embedded modules in repositories, vital updates existing modules. then ...
  * Developer can also specify adding modules / removing modules.
  * Vital shows destructive changes if embedding modules contain them.

**Comment by umireon** [comment]
Thank you for the detailed technical description, @tyru.
I got your point that vital.vim is a module bundler in Vim.
So, how can I bundle vimproc to my plugin with vital.vim?

**Comment by tyru** [comment]
vital.vim can bundle only "modules."
vimproc is not a vital module. so you can't.
"Modules" are Vim script file which *may* have special functions, like `s:_vital_loaded()`.

If you have Vim 8+, I recommend +job feature than vimproc.
See :help +job

**Comment by tyru** [comment]
> Please describe what vital.vim provides \*with a paragraph\*

1. http://howivim.com/2016/tyru/
1. http://tyru.hatenablog.com/entry/2016/04/25/205143

2 is Japanese so we cannot add the link to this repository though...

**Comment by umireon** [comment]
I just have read both articles.

Do you mean vital.vim consists of the two components:
* (Major) A breezing-fast module bundler to unclutter versioning in Vim, named vital.
* (Minor) A selected collection of good Vim scripts in the form of vital modules.

**Comment by tyru** [comment]
Yes.
But I don't care about which is a major / minor feature. I think both are important when a developer makes a Vim plugin seriously.
And module bundler is called **vitalizer**.

**Comment by tyru** [comment]
ここで話した内容を README.md あたりに書こうと思うのですが、どうでしょうか？ >ALL
以下ちょっと気になる点です。

* `What problems does vital.vim solve?` は `What vital.vim aims for?` とかシンプルに `Problems` のがいい気もする。
* この issue へのリンクは必要？ほぼ全文引用してあるから必要ない？

以下が README.md に載せる例です。

# What problems does vital.vim solve?

At the beginning of vital.vim, vital.vim is the library to just cover the poor Vim script capability.
But in Vim script, using external library brings another problems:

* Does the library place to single repository or not?
* If the answer is "Yes"
  * Updating the library is tedious
  * Checking destructing changes are super tedious
* If the answer is "No"
  * User must install it manually
  * There is no version locking system in Vim script

The above problems are only when **one** library depends no other libraries. If the library depends other libraries or when using multiple libraries, the problems become more complicated. vital.vim solves the above problems.

# How vital.vim solves this?

vital.vim solves the above problems by:

* vital.vim **embed** libraries into developer's repository so plugin users don't have to install manually, and also there is no need to care about the versions of the libraries.
* Vital "modules" can depend other "modules".
* When embedding modules, vital resolves the dependencies and install only necessary modules.
* If there are already embedded modules in a repository, vital updates existing modules. then ...
  * Developer can also specify adding modules / removing modules.
  * Vital warns destructive changes which embedding modules have.

**Comment by umireon** [comment]
I finally grasped that vital.vim is virtually a mixture of two repositories (the module bundler named **vitalizer** and a supplemental library called **vital.vim**) and has the same structure as [Homebrew/legacy-homebrew](https://github.com/Homebrew/legacy-homebrew) does.
Thank you for clarifying 😍 

By the way, as a newbie on vital.vim, what feature the module library **vital.vim** provides?
I'm not so much interested in **vitalizer** itself because I have never met the versioning problem yet..

**Comment by tyru** [comment]
> a mixture of two repositories

s/repositories/components/ or s/repositories/features/ ? :-)
Currently, vitalizer (autoload/vitalizer.vim) and set of modules (under autoload/vital/__vital__) are all in this repository.

> what feature the module library vital.vim provides?

See this: https://github.com/vim-jp/vital.vim#what-vitalvim-provides

**Comment by umireon** [comment]
> s/repositories/components/ or s/repositories/features/ ? :-)

s/virtually a mixture of two repositories/a mixture of two virtual repositories/
This structure will end up with two separate repository as [Homebrew/brew](https://github.com/Homebrew/brew) and [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core).

> See this: https://github.com/vim-jp/vital.vim#what-vitalvim-provides
This does not describe anything as stated in the first comment.

**Comment by umireon** [comment]
I think the vital library is a set of text processing functions plus PRNG.
Is it correct?

**Comment by tyru** [comment]
> what feature the module library vital.vim provides?

To be honest, there are no intentions for what to provide.
So *comprehensive* is not wrong. or... it's more like *miscellaneous*? :-/

Or you can think like this: if you wrote a Vim script functions as vital module, you can gain ecosystem benefits of vitalizer.

**Comment by umireon** [comment]
> So comprehensive is not wrong. or... it's more like miscellaneous? :-/
The word *comprehensive* is very misleading and I think the usage of it on this project is even wrong.
The word comprehensive means that everything in the (Vim) world and that is apparently not true.
If vital.vim is aiming at Vim equivalent of [CTAN](https://www.ctan.org/), the usage of comprehensive can be justified.

Note that Boost is the probable equivalent of vital.vim in C++ and this project can be described as opinionatedly as they does.

**Comment by umireon** [comment]
Boost is a C++ library to supply the missing part in standard C++ that is the same target vital.vim aims at.
Although Boost has [a larger set of libraries](http://www.boost.org/doc/libs/1_63_0/) by far than vital.vim has, they have many good brief descriptions such as [one on Wikipedia](https://en.wikipedia.org/wiki/Boost_(C%2B%2B_libraries)), which helps people greatly understand what it is.

**Comment by umireon** [comment]
So, vital.vim provides the missing libraries in Vim such as text processing, pseudo random number generation, data structure manipulation and network connectivity with the well-defined module version manager?

**Comment by tyru** [comment]
> So, vital.vim provides the missing libraries in Vim such as text processing, pseudo random number generation, data structure manipulation and network connectivity with the well-defined module version manager?

Brief good description :)
Hmm... we should add the brief description and `Problems` and `How to solve this?` sections
to the top of README.md, and project description (header of top page of repository)?

> A comprehensive Vim utility functions for Vim plugins.
> This is like a plugin which has both aspects of Bundler and jQuery at the same time.

I think we can replace this sentence.

**Comment by tyru** [comment]
Added `Introduction`. https://github.com/vim-jp/vital.vim/issues/474#issuecomment-272857725

**Comment by tyru** [comment]
Added `TODO`. https://github.com/vim-jp/vital.vim/issues/474#issuecomment-272857725

**Comment by tyru** [comment]
ちなみにこんな感じになります。

![0b7d32f84a4a5bd5aeaf4e0d2ee7ff22](https://cloud.githubusercontent.com/assets/48169/21988569/1c84bdf0-dc4b-11e6-8531-1c0f946f3626.png)

**Comment by haya14busa** [comment]
I'm really :+1: to add a description to README based on the conversation in this issue.

We don't clearly state that which is major feature, but I think we can safely say that a key differentiated killer feature is vitalizer which embeds (or vendor?) vital modules into Vim plugins. Vim plugin users doesn't need to do anything (like installing a library plugin). 

You can find other useful Vim script libraries by googling and quality may be good, but most of them requires users to install libraries and doesn't solve version compatibility problem as far as I know.

In addition, we didn't add clear document yet, but you can create "external" vital modules. You don't have to add your module to vital.vim repository. (btw, you can also use any licence for external modules as far as i understand)

i think it might be better to note that this feature.

**Comment by umireon** [comment]
The first brief description should be shortened further like:
_Unclutter Vim module bundling with our quality libraries_

**Comment by tyru** [comment]
![bbd4fbd8fef09dc97dbb4d15546a4e55](https://cloud.githubusercontent.com/assets/48169/21989336/da641ea4-dc4d-11e6-8cf0-37bf81bfffc7.png)

**Comment by tyru** [comment]
一応忘れないために…元の説明文はこれです。

```
A comprehensive Vim utility functions for Vim plugins
```

**Comment by umireon** [comment]
The logic in the problem statement is unclear. That should be like:

# Handling modules in Vim WAS hard
Since Vim script has no built-in module systems, using external community modules had been troublesome.
* If you decide to include the community modules in your plugin distribution:
  You are responsible for updating the community modules by yourself. *sigh*
  You have to ensure the updated module would not spoil your plugin. *super tedious*
* If you want the plugin users to install the dependent community modules: 
  The users will receive additional steps to get worked with your plugin. *not easy*
  Even worse, they may fail to install the dependencies properly. *a bad dream*

**Comment by umireon** [comment]
Some editorials.

# What vital.vim does for this problem
**vital.vim** will embed libraries into your plugin distribution and thus your plugin users need not install them separately.
Additionally, **vital.vim** can also resolve the dependency according to the declaration on **vital** modules.

Concretely, **vital.vim** resolves the dependencies among **vital** modules by its module bundler called **vitalizer**.
**vitalizer** can bundle necessary modules only and can update an existing bundle.
On updating, **vitalizer** shows any breaking changes to help you migrate to the new version of **vital** modules.

**Comment by tyru** [comment]
いい感じですね。
確かに vital.vim の歴史的経緯とかいらない情報が削ぎ落ちて簡潔になった感じです。
（ハイテンションな感じの文章がフィットするかは肌感覚ないので誰か他の人にツッコミ及び判断任せるとして…）

* community modules の community はどのような意図で付けてるのでしょうか？
* plugin distribution は単に plugin あるいは Vim plugin でいいんじゃないでしょうか。
* あとすみません、言い忘れてましたが、vitalizer は**インストールする前に**破壊的変更をリストアップしたあと、プロンプトを出して本当にインストールするか確認してくれます。

**Comment by umireon** [comment]
> （ハイテンションな感じの文章がフィットするかは肌感覚ないので誰か他の人にツッコミ及び判断任せるとして…）

Addressing the reader as *you* is a useful expression in a use case or a problem statement.
*sigh* is typical superfluous thingy, though ;)

> community modules の community はどのような意図で付けてるのでしょうか？

I replaced *external* with *community* because the word *external* is a bit ambiguous to mean that the author does not possess the module.
Just removing *community* will be okay.

> plugin distribution は単に plugin あるいは Vim plugin でいいんじゃないでしょうか。

By the word *distribution*, I mean the embedded libraries will be delivered to the users, and it is used in place of *repository*.
My vocabulary is primarily based on the TeX community, and I'm not sure my wording is acceptable in the Vim community.

> あとすみません、言い忘れてましたが、vitalizer はインストールする前に破壊的変更をリストアップしたあと、プロンプトを出して本当にインストールするか確認してくれます。

I agree that is a great feature to be documented, but we should not describe everything in the introductory sections.
IMO what we should say here is just *vitalizer* protects the author from unexpected breaking changes.

**Comment by ujihisa** [comment]
> with our quality libraries

Subjective adjectives such as easy, simple, quick, awesome, or quality, can be noisy. It should focus more on what it solves.

**Comment by umireon** [comment]
@ujihisa Yes, I'm definitely with you 👍.
I haven't yet gotten a clear concept what problem the vital **module library** are intended to solve.
That is why I have to use subjective wordings such as quality, comprehensive and utility.
Moreover, the verb **unclutter** is not familiar to Japanese and hard to understand.

**Comment by tyru** [comment]
> Just removing community will be okay.

OK.

> I'm not sure my wording is acceptable in the Vim community.

Vim だと plugin distribution は [janus](https://github.com/carlhuda/janus) みたいにいくつかのプラグインをまとめたプラグインのことを言うと思うので、plugin の方が適切かと思います。

> we should not describe everything in the introductory sections.

OK.
