### ISSUE TITLE
Vim 8.0.0219 以降で Bitwise がうまく動かない

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#479]
```
patch 8.0.0219: ubsan reports errors for overflow

Problem:    Ubsan reports errors for integer overflow.
Solution:   Define macros for minimum and maximum values.  Select an
            expression based on the value. (Mike Williams)
```

詳しいことはわかっていないが、どうやらオーバーフローするリテラルがオーバーフローしないような調整が入った?
master のテストが落ちているので早めに直したい。

**Comment by k-takata** [comment]
http://lingr.com/room/vim/archives/2017/01/30#message-23837125
lingrで議論したとおりで、リテラルの数値として扱えるのは、 0 ～ 0x7FFF_FFFF_FFFF_FFFF ということになります。(負の数は、これに対して符号を付けるので、-0x7FFF_FFFF_FFFF_FFFF ～ 0)
0x8000_0000_0000_0000 を超えたものはすべて丸められます。

**Comment by thinca** [comment]
おおお、自分から振っておいて完全にログを見落としていました…! すいません& ありがとうございます! 🙇

**Comment by k-takata** [comment]
直し方としては 0x8000_0000_0000_0001 ～ 0xFFFF_FFFF_FFFF_FFFF の数値が必要であれば、 -0x7FFF_FFFF_FFFF_FFFF ～ -1 に置き換えることになるのではないでしょうか。
0x8000_0000_0000_0000 は、 -0x7FFF_FFFF_FFFF_FFFF - 1 か 0/0。

**Comment by thinca** [comment]
#481 で修正されました！
