### ISSUE TITLE
Data.Eitherを作りたい

### ISSUE THREAD

**Issue by aiya000** [vim-jp/vital.vim#499]
タイトルの通りですが、Data.Eitherモジュールを作りたいです。

　Data.Eitherは、基本的にHaskellのEither型の振る舞いを真似て作っていきます。  
Scalaの標準Eitherの方は考えないことにします。
外部モジュールとして作成することも考えたのですが、それなら公式に含めて貰った方が嬉しいなーと思って、この申請を行います。

　このモジュールのメンテナに関しては、僕を使って頂くのでも、他の方に担当してもらうのでも構いません。  
都合がいい方で ❗️ 

　これは（例外を扱わないという意味での）純粋関数の作成をサポートする目的で作られます。  
我々はEitherを使うことで、不用意な例外の送出によって、挙動を遅くすることを回避することができます。

**Comment by aiya000** [comment]
ブランチです。

[aiya000/vital.vim at create_data_either](https://github.com/aiya000/vital.vim/tree/create_data_either)

**Comment by aiya000** [comment]
とりあえず、実装とドキュメントは作りました。

**Comment by tyru** [comment]
自分は別に vital に含めてもいいと思います。
PR 送ってくれたら見ます！
 
チラッと見て .flatmap() ほしさを感じましたが、どうせなら他のモナドも受け取れたりしたいので、型のない Vim script でどのように定義するかがちょっとちゃんと考えないといけなさそうですね…
ちなみに自分は Haskell やったことないのでﾓﾅﾄﾞﾁｮｯﾄﾜｶﾙとかじゃなく本当にモナド分かりません。
ここらへん斜め読みした程度です。
http://qiita.com/suin/items/0255f0637921dcdfe83b

**Comment by tyru** [comment]
> このモジュールのメンテナに関しては、僕を使って頂くのでも、他の方に担当してもらうのでも構いません。

あいやさんコミット権ないんでしたっけ。
あげてもいいと思うのですがどうでしょう >ALL

**Comment by thinca** [comment]
いいのよ。

**Comment by ujihisa** [comment]
いいのよ。

**Comment by ujihisa** [comment]
コミッタinvitation送ってみました。

**Comment by mattn** [comment]
いいわよ。

**Comment by tyru** [comment]
> .flatmap() ほしさ

あ、別に either.flatmap(a) で a が他のモナドであることを考慮する必要はないのか…
either.flatmap(either2) みたいに単純に Either 用
の flatmap() なんだから別に設計考えなきゃいけないみたいな話ではなかった。
のでできれば追加してほしさがあります。 >@aiya000
（もしモナドの知識が間違ってたら指摘してもらえると助かります）

**Comment by tyru** [comment]
.flatmap() か .flat_map() かという問題もある…

**Comment by aiya000** [comment]
hi, コミット権ありがとうございます！  
コミット権頂けたので、とりあえずメンテナは僕に指定させていただいた方がよさそうかな。 問題とかがあればお願いします！

**Comment by aiya000** [comment]
.flatmap()ですが、おそらく.bind()が同等になるかと思います！  
（実際、Haskellのリストモナドのモナドバインドの実装はconcatMapだったり）

確かにおそらく人々が探すときは、flatmapというワードを使いそう。  
.bind()へのエイリアスとして、.flatmap()を追加しようかな。

**Comment by aiya000** [comment]
あ、一般的なモナドの性質（.bind()）では、他のモナドを受け取っても平坦にすることができないので、その場合の動作は未定義としておいた方がいいなーと思ってます :thinking:

**Comment by tyru** [comment]
ふむふむなるほど。
`>>=` のことをバインドっていうんですね。
.bind() があるならそれで構わないです。

モナド則を見る限り、モナドっぽいものを実装する時は .bind() とあと .return() を実装すると統一的に扱える？
となると .return() もできれば…！
http://qiita.com/south37/items/06cfa95aa9c8f2ecb2e9

（ただ他の型のモナドを統一的に扱えると嬉しいケースが分かってないです。そこまでの抽象度がほしいケースってどんなケースなんだろう…）

**Comment by aiya000** [comment]
個人的にも.flatmap()は載せておいた方がいいかなーと思うので、問題がなければ載せたいのですが、どうでしょう。

- - -

　例えばData.OptionalとData.Eitherのどちらもが以下の関数を実装していれば、モナド自体を引数に取る関数を、統一的に扱える……ということができそう :thinking:  
もしvital.vimで`Control.Monad`（`Data.Monad`のがいいのかな？）を実装するときがあれば、そのときにだいぶ捗りそう。  
（実はあまりそういうプロトコル的なものを共有するのは考えてなかった…）

- Monadが実装してると良さそうな関数（多分）
    - .return(x)
    - .bind(m, fm)
    - .join(mm)

（Vim scriptにinterfaceのデフォルト実装的な機能がないので、各々これら全てを実装する必要はありそう）

**Comment by aiya000** [comment]
なんかわからんけど、tyruさんが示した利点を復唱してた :bow:

**Comment by tyru** [comment]
追加すること自体は全然構わないです。
最終的にどちらを統一的なインターフェースにするかは後々決めたいですが…

おお、join なんてのも必要になるんですね。調べてみます。

**Comment by aiya000** [comment]
joinはいいですよ、モナドの最もたる特徴なんですよ〜最高。  
一応実装済みです！

**Comment by aiya000** [comment]
全部終わったので、PR投げてみました 😋

**Comment by tyru** [comment]
お疲れ様でしたー
