### ISSUE TITLE
ドキュメントを用意する

### ISSUE THREAD

**Issue by Shougo** [vim-jp/vital.vim#5]
さすがに、まともなライブラリとして使用するには、ドキュメントが必須だと思います。
私でさえ、すべてのモジュールの使用は把握していません。
ひとまず、これをベースにドキュメントを整えるのが良いのではないでしょうか。

http://d.hatena.ne.jp/kanno_kanno/20120107/1325949855

**Comment by ujihisa** [comment]
vitalizerはdocあるのであとはcoreのdocだけかな?

**Comment by ujihisa** [comment]
https://github.com/vim-jp/vital.vim/issues/279
