### ISSUE TITLE
Should we use Data.Closure in Stream module?

### ISSUE THREAD

**Issue by tyru** [vim-jp/vital.vim#503]
ref. https://github.com/vim-jp/vital.vim/pull/498#issuecomment-299714640

> 1. Should Data.Closure be supported as dependency?

ということで Data.Closure を Stream で使うべきか決めるスレです。
Data.Closure は `v:val` の代わりに `a:1` を使うので互換性の問題もある、と
@thinca さんに Lingr で聞いたので、~マージ前にこの issue で決めた方がいいかと思いました。~
やはりこの issue で出た議論は ver.2 向けのもので、Changes に書く予定にしましょう。

Link: http://lingr.com/room/vim/archives/2017/05/07#message-24031055

**Comment by tyru** [comment]
ping @thinca @rhysd @haya14busa

**Comment by tyru** [comment]
@rhysd @haya14busa #498 マージするする詐欺ですみません。
@thinca さんが Data.Closure の議論に加わってなくて、Lingr で聞いたら互換性の問題があるとのことだったので、

**Comment by tyru** [comment]
> @rhysd @haya14busa #498 マージするする詐欺ですみません。
> @thinca さんが Data.Closure の議論に加わってなくて、
> Lingr で聞いたら互換性の問題があるとのことだったので、この issue を作りました。

すみません、やはりこの issue で出た議論は ver.2 向けのもので、Changes に書く予定にしましょう

**Comment by rhysd** [comment]
僕自身は `Data.Closure` 使ったこと無くてよく分かっていないので，この件は識者にお願いします

**Comment by thinca** [comment]
`Data.Closure` を使う最大のメリットは、関数として呼び出したい対象 (文字列でも Funcref でも `Data.Closure` オブジェクトでも) を `Data.Closure.call()` に放り投げれば全てよしなにしてくれるところです。分岐する必要はないです。
これによりコードをシンプルにすることができ、かつ対応できるパターンが増えます。例えば foldl に対して `'+'` と言う文字列を 2 引数の関数として渡せます。

ただ、正直に言うと、現状は内部で毎回 `Data.Closure` オブジェクトを構築してから呼び出しを実行しているので、分岐を除いても若干オーバーヘッドがあります。ここは将来的には必要なければオブジェクト構築をせずに呼ぶなど最適化したいところです。(ただそもそも現状 `Data.Closure` 自体あまり利用されておらず…)

**Comment by aiya000** [comment]
以下の観点から、使うことに+1 :+1:

- 使わない理由がない気がするような
- Vim scriptに速度を求めるのは不毛な気がするので、オーバーヘッドを気にしてもメリットが勝つような
    - vital.vimの多くのモジュールがData.Closureを使うようになれば、文字列式の記法の乱れが抑制できる（統一したい）
        - v:val, a:1
        - 'v:memo + v:val', 'a:1 + a:2'（Data.List）
- めっちゃ便利

**Comment by tyru** [comment]
自分が気にしているのは速度の問題で、Vim script だからといって速度を気にしなくてもいい、ということにはならないと思います。
速度を気にするべきかしなくてもいいのかは用途によるはずです。

**Comment by aiya000** [comment]
もちろん速いに越したことはないんですが、それよりももっと大切なことがあるんじゃないかという感じです。  
速度を求める場合は外部インターフェースを使うと思ってて、それ故です。

まあでも、もしtyruさんが速度をなによりも大事にしたいならData.Closureは使わない方がいいのかもですね。

**Comment by aiya000** [comment]
このissueの背景がいまいちよくわかってなくて、もしかして「Data.Closureを使う必然性はないけど、使った方がいい理由はある？」ってことなんですかね？  

依存性を除去するために、Data.Closure相当の処理を自前で作るか？
それともData.Closureに依存するか？
というのを考えてました。

**Comment by tyru** [comment]
> このissueの背景がいまいちよくわかってなくて、もしかして「Data.Closureを使う必然性はないけど、使った方がいい理由はある？」ってことなんですかね？

そうです。
で、Data.Closure に依存するなら互換性を壊すことになるけど、それを乗り越えてでも導入する必要はあるか？という経緯でした。
Stream モジュールの PR で話し合うのは分量的に無理だったので、別でこの issue を作りました。
なので vital モジュール一般の話ではなく、あくまで Stream モジュールでの話です。

**Comment by aiya000** [comment]
なるほど！

でしたら、不必要な依存を持つ必要はないかなーと思います :thinking:

**Comment by thinca** [comment]
速度を気にするのであればベンチマーク取った方がいいですね。

**Comment by rhysd** [comment]
この issue の背景は一番最初は @haya14busa さんのコメントで，「funcref に対応していれば直接 Data.Closure 向けのコードを入れる必要は無いのでは？」という点でした．

https://github.com/vim-jp/vital.vim/pull/498#discussion_r115111753

Data.Closure がある時とない時の差分は @tyru さんのコメント https://github.com/vim-jp/vital.vim/pull/498#discussion_r115112608 によると

- あるとき

```vim
let s:C = vital#of('vital').import('Data.Closure')
echo s:Stream.of(1,2,3).map(s:C.from_expr('a:1 * 2')).to_list()
```

- ないとき

```vim
let s:C = vital#of('vital').import('Data.Closure')
echo s:Stream.of(1,2,3).map(s:C.from_expr('a:1 * 2').to_function()).to_list()
```

この程度の違いなら直接 Data.Closure への依存を増やさなくても良いんじゃね？ということでした．
要は，Stream が直接 Data.Closure をサポートすることで得られる恩恵が依存を増やしてまで得るべきものかどうか？というのが論点だと思います。

ベンチマークなしにパフォーマンスの議論するのはあまり意味がないです。

**Comment by thinca** [comment]
本件がこじれてるのは、私が最初に `Data.Closure` を提案したときに、メリットについて詳しく説明しなかったからかと思います。すいません。
で、メリットについては本 Issue で[説明しました](https://github.com/vim-jp/vital.vim/issues/503#issuecomment-299818905)。わからないところがあれば聞いてもらえれば。
で、内部的に `Data.Closure` で処理を行うように対応してあれば、`Stream` の利用者は `Data.Closure` の `{callable}` について知っていれば、別途 import の必要はなくなります。例えば @rhysd さんが示してくれた例だと、利用例は以下のようになるはずです。

```vim
echo s:Stream.of(1,2,3).map('=a:1 * 2').to_list()
```

メリットについては説明したので、最終的に導入するかは @tyru さんにお任せします。

---

お任せしますと言っておきながら個人的な意見も。
vital は汎用的なライブラリを提供しているライブラリ集で、ライブラリとはコードの再利用を目的としているものです。再利用が目的なのに、「依存が増えるから」と言う理由で再利用が行われない風潮を最近感じていて、なんだかなぁともにょもにょしてます。
依存が増える = 読み込むコードが増える = Vim script が遅いので、全体が遅くなる、みたいなのを気にしてそうなっているのかなーと思ってますが、それなら vital はただのコードスニペット集でいいじゃんってなるので、必要だと思う箇所では恐れずに依存してほしいなーと思ってます。

**Comment by rhysd** [comment]
いえ，依存が増えるから駄目と言っているのではなくて，依存増やすならそれに見合った恩恵があるかどうか検討すべきということを言っているだけです．

**Comment by thinca** [comment]
> 依存増やすならそれに見合った恩恵があるかどうか検討すべき

これのしきい値が高くなっている印象があるんですよね。完全に主観で申し訳ないんですが。余程のことがないと依存しない方向になっている気がします。他言語なら、依存を増やすのにそこまで慎重にはなってないと思うんですよね。無駄な依存を増やす必要はもちろんないですが、もっと気軽に依存増やしてもいいんじゃないかなーと。
(繰り返しますが主観なのでこの話はここまでにした方がよさそう)

**Comment by tyru** [comment]
了解です。
Data.Closure を使うことで遅くなるかはベンチマーク取って試してみます。
それ次第で導入するか検討します。

* （.to_function() を噛まさなくて良くなるのは魅力的なので、前向きに検討中）
  * Before: Stream.iterate(1, 'v:val + 1').take(100).reduce('v:val[0] + v:val[1]')
  * After: Stream.iterate(1, '=a:1 + 1').take(100).reduce('+')
* （なんなら内部で .to_function() して Funcref で持っておけばいいそんなにオーバーヘッドないのではとか今更ながら）

**Comment by mattn** [comment]
![FF外から失礼します](https://cloud.githubusercontent.com/assets/10111/25890959/549a7082-35aa-11e7-84fe-1dc0bbf4b5f7.jpg)

依存を増やさない場合、プラグイン作者自身が lambda をサポートしていないバージョンを救うかどうかを選べるけど、依存を増やす場合は Data.Closure の import に掛かるタイムロス(未計測でしゃべるな)を後方互換を無視する覚悟で解除する自由があってもいいんじゃないかなーと思いました。

**Comment by haya14busa** [comment]
ところで Data.Closure の文字列を受け取って内部で関数作る場合, "Closure" の部分の機能が完全に消える、もし変数キャプチャしたいとかなると、Data.Stream に l: とか渡せるようにしないとだめになると思いますが認識正しいですかね?

僕は https://github.com/haya14busa/underscore.vim 作ったときに Data.Closure も一緒に使っていくつかscript書いてみましたが、変数キャプチャはないと正直ほとんど使い物にならない感がありました。
かといって Data.Closure に l: 渡すのも比較的面倒だし、s: は結局使えないのもつらかったです。

v:val で map() の hack で呼び出す場合も同様の問題があるんですが、その問題を解決せず、
v:val が a:1, a:2 になるのは結構なんですが、なんというかそこまでのメリットを感じてないです。

そんで Vim 8, しかも最近はどうやら nvim にもとっても便利な lamda っていう上記の問題を解決してくれる素敵ソリューションがあって、Data.Stream を真面目に使えるとしたら個人的には間違いなくlambdaと一緒に使うようになると考えてます。Data.Steamっていう今からできる、比較的チャレンジングなことやってるモジュールを使ってどうしても7.4対応もしたいっていう人はそこまでいないのではないか、という印象ですし。

なので個人的には文字列のほうは、言ってしまえば割りとどうでもいいと考えてて、そうなるとあんまりメリットもないのに依存増えて、しかもオーバーヘッドもある。となるとウーン...という気持ちです。

**Comment by tyru** [comment]
@mattn Stream.require_closure() みたいなメソッド呼ぶと Data.Closure 使うインターフェースになるみたいな感じですかね？

**Comment by mattn** [comment]
@tyru lambda をサポートしないバージョンをサポートしたいプラグイン作者は `s:Stream.of(1,2,3).map(s:Closure.from_expr('a:1 * 2'))` で呼び出すんじゃないですかねー。ただ haya14busa さんが言うように使いにくさはあると思いますが。

**Comment by tyru** [comment]
@mattn 渡された値の型によって Closure が必要な型（文字列）だったら初回に import する、みたいな感じですかね？
ちなみに Funcref を渡したい場合は
```viml
s:Stream.of(1,2,3).map(s:Closure.from_expr('a:1 * 2').to_function())
```
ですね (from_expr() までだと closure object)。

**Comment by tyru** [comment]
@haya14busa 一応文字列であっても演算子渡せたり関数名渡せるのは割と便利なんじゃないかと思います。

```viml
echo s:Stream.range(1, 100).reduce('+')
echo s:Stream.of("a", "bb", "ccc").max_by('*len')
```

ただ確かに大抵のケースで lambda 使えるなら使った方がスマートに書けるのは同意です。

**Comment by tyru** [comment]
@haya14busa 

> もし変数キャプチャしたいとかなると、Data.Stream に l: とか渡せるようにしないとだめになると思いますが認識正しいですかね?

`l:` は現状でも渡せるみたいです。
https://github.com/vim-jp/vital.vim/blob/9883e246977883ad0c633ce295faf4c67d597d05/doc/vital/Data/Closure.txt#L54-L64
https://github.com/vim-jp/vital.vim/blob/aabb291268c0977e1444b0901e816db4467d6806/test/Data/Closure.vimspec#L108-L115

Stream で `l:` 渡すとしたら map() とかの高階関数の引数に渡すか `map(...).bind(l:)` みたいに .bind() ってメソッド作ってバインドできるようにするかですね。

**Comment by tyru** [comment]
うおお… 思ったよりずっと Data.Closure 遅い…
自分の使い方が間違ってるでしょうか？ >@thinca 
https://gist.github.com/tyru/4b9d803bfadc093911ad14547a47f8aa

**Comment by tyru** [comment]
結構多くの事やってますね… ここら辺が（.to_function() した関数が特に）重い原因な気がします。
https://github.com/vim-jp/vital.vim/blob/9ef73cc9775d9e03ab1943f1bb3edaead54ecb43/autoload/vital/__vital__/Data/Closure.vim#L133-L145

**Comment by mattn** [comment]
僕が考えていたのは、Stream 側の変更は行わないって意味です。lambda をサポートしないバージョンを救いたい人だけが Data.Closure を使えばいい、という事です。

**Comment by rhysd** [comment]
@tyru さんのベンチマークを僕の手元でも試してみました

- Data.Closure なし

```
s:sum_pure(100000):   0.254392
s:sum_stream(100000):   1.073294
```


- `data-closure.diff`

```
s:sum_pure(100000):   0.265534
s:sum_data_closure(100000):   6.384345
```


- `data-closure-2.diff`

```
s:sum_pure(100000):   0.259001
s:sum_data_closure(100000):   3.807670
```

> これのしきい値が高くなっている印象があるんですよね。完全に主観で申し訳ないんですが。余程のことがないと依存しない方向になっている気がします

気のせいだと思います．元々他のモジュールに依存しているモジュールがあまり無い中で，偶然 Optional だか Either だかの件とこの件が2つ連続したからそう思うだけじゃないでしょうか．いずれにせよ，問題だと感じるのであれば別に issue を立てたほうが良いと思います．

**Comment by rhysd** [comment]
@tyru さんがベンチマークのたたき台をつくってくれたのでもう少し見てみました

## ラムダ式を渡した場合

実装はこんな感じ

```vim
function! s:sum_data_closure_lambda(n) abort
  echo s:Stream.range(1, a:n)
              \.reduce({a, i -> a + i}, 0)
endfunction
```

### Data.Closure あり

```
s:sum_pure(100000):   0.254317
s:sum_data_closure_lambda(100000):   3.840495
```

### Data.Closure なし

```
s:sum_pure(100000):   0.252800
s:sum_data_closure_lambda(100000):   0.799379
```

---

ラムダ式を渡した時にこれだけパフォーマンスが劣化するのは受け入れがたいです．

```vim
function! s:Stream.reduce(f, ...) abort
  if type(a:f) == s:T_STRING
    let l:Func = s:_build_closure(a:f)
  else
    let l:Func = a:f
  endif

  " ...

endfunction
```

みたいに分岐する必要が出てくるのではないでしょうか

**Comment by tyru** [comment]
うーん正直これだけ遅くなると Data.Closure 入れたくないですね…
Stream モジュールでは大量のリストを処理する可能性もあるので、なるべく素の Vim script で書いた時になるべく近付けたいです（素で書くよりシンプルに、かつできれば素で書くより速い場合もある？みたいな…（予定））。

**Comment by thinca** [comment]
遅いだろうなとは思ってましたが、これほどだとさすがにつらいですね…。
そもそも (お察しの通り) `Data.Closure` は lambda がない時代に苦肉の策として作られたモジュールなので、ターゲットを Vim 8.0 以降をメインターゲットにするのであれば、全く必要ないです。
むしろ関数として受け付けるのは `Funcref` だけにして、文字列式自体サポートしなくてもいい気すらします。その方がシンプルですし。

**Comment by tyru** [comment]
うーん一応 vital の一モジュールなので Vim7.4 はサポートしたい感じです（Vim 8 の機能を使ったモジュールならともかく、そうでないなら vital の互換バージョンに合わせたい）。
で、Vim 7.4 で Funcref を渡すにはわざわざ :function コマンドで関数を作る必要があるので、できれば文字列式をサポートしたいですね…

**Comment by mattn** [comment]
@tyru そこで

>むしろ関数として受け付けるのは Funcref だけにして、文字列式自体サポートしなくてもいい気すらします。その方がシンプルですし。

という意味だと思うのですが

**Comment by tyru** [comment]
@mattn えっとすみません、Data.Closure を使う場合の話ですか？>to_function
thinca さんとの話の流れで Data.Closure は使わない方がいいという話になっていたと思ってました。

**Comment by mattn** [comment]
### lambda が使える場合

    lambda を使う

### lambda が使えない場合

    後方互換性を救いたいプラグイン開発者は Data.Closure を使う

でいいと思います。つまり関数リファレンスを引数でいいと思います。

**Comment by tyru** [comment]
それだと lambda を使えない Vim 7.4 では

* 遅いのを覚悟して Data.Closure を使う
* 冗長だが :function で関数を定義する

という選択肢になりますが、それはしょうがないという意味でしょうか？

**Comment by mattn** [comment]
遅いのはインポートと関数の作成部分だと思います。Stream の関数を呼ぶ度に作っていたら遅くなって当然かと思います。それを再利用可能な様に呼び出し側で持っておけばそんなにひどいベンチマーク結果にはならないと思います。

**Comment by tyru** [comment]
> Stream の関数を呼ぶ度に作っていたら遅くなって当然かと思います

関数というのは .map(f) でいう f の事でしょうか。
だとしたら f を呼ぶ度には作っておらず、.map() を呼んだ時点で .to_function() してその Funcref を作っておいてあります。
なので 100000 万回呼ばれるのは .to_function() で作られた関数です。

**Comment by tyru** [comment]
s/100000 万回/10 万回/
呼びすぎた…

**Comment by mattn** [comment]
なるほど。to_function してるのになぜ遅いんでしょう？

**Comment by tyru** [comment]
なぜでしょう…
ついでなので帰ったらちょっとベンチマーク取ってみます。

**Comment by tyru** [comment]
ベンチマークというかプロファイルでした。
プロファイルを取った結果（profile.sh を実行した結果）、以下の順に遅い事が分かりました。

8.4 秒のうち：

1. `s:_eval()` (2.2 秒)
1. .to_function() で定義される関数 (2.1 秒)
1. `s:_move()` (1.5 秒)
1. `s:_is_closure()` (1.3 秒)

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
100000   3.694310   2.201085  <SNR>6__eval()
100000   8.409259   2.174540  <SNR>6__function_1()
100000              1.493225  <SNR>6__move()
100001              1.304419  <SNR>6_is_closure()
100000   4.473834   0.779524  30()
100000              0.456478  38()
    2              0.000081  <SNR>6__sfunc()
    2              0.000072  <SNR>6__get_arglist_and_context()
    1   0.000346   0.000046  <SNR>6_build()
    2   0.000131   0.000041  34()
    1   0.000113   0.000041  36()
    1              0.000031  <SNR>6__make_function()
    1   0.000200   0.000028  <SNR>6_from_expr()
    1   0.000232   0.000028  <SNR>6_from_operator()
    1   0.000116   0.000022  <SNR>6_from_funcref()
    1              0.000018  <SNR>6__new()
    1              0.000014  <SNR>6_sweep_functions()
    2              0.000009  <SNR>6__is_operator()
    1              0.000006  <SNR>6__create_function_id()
    1              0.000005  <SNR>6__get_binding()
```

やっぱり Vim script の性格上、行数が多くなると単純に遅くなってく、という結果のように個人的には思います。

**Comment by mattn** [comment]
今はまだ funcref と文字列の両方をサポートする処理なのですか？

**Comment by tyru** [comment]
そうです。
ちなみに d127fe6ae3ca25fa7902b9e43f970bef340cd7ed に対して Gist のパッチ（data-closure.diff）を当てて試しました。

**Comment by tyru** [comment]
Stream のベンチマークを Stream で計測してみました（よく分からない）。
ベンチマーク用のスクリプトは bench.vim に分離して、startup.vim から system() で Vim を立ち上げてベンチマークするよう変更しました。
https://gist.github.com/tyru/4b9d803bfadc093911ad14547a47f8aa/839d9ebd782f965b7a13ece8a5957eb8368f90ef
あと色々変えました。変えすぎました（Stream をテストするためという建前があり Stream をそこかしこで使いまくってます）。

output.txt に出力を載せましたが、いちおう

```sh
git clone {vital} vital.vim
cd vital.vim
git clone {gist} data-closure-bench
bash data-closure-bench/bench-all.sh
```

で実行できます。

**Comment by tyru** [comment]
ちなみにプロファイルの取得は `DO_PROFILE=1 bash data-closure-bench/bench-all.sh` でできるはずです。

**Comment by tyru** [comment]
https://github.com/vim-jp/vital.vim/pull/504#issuecomment-301296300 から引用。

> ref. https://github.com/vim-jp/vital.vim/issues/503#issuecomment-300964581
> @thinca さんから
> 
> > むしろ関数として受け付けるのは Funcref だけにして、文字列式自体サポートしなくてもいい気すらします。その方がシンプルですし。
> 
> というアドバイスがありましたが、計測してみたところ 10 万回のループで 0.1 sec で、まぁ誤差の範囲ではないけど許容できるレベルかな…と判断しました。

**Comment by tyru** [comment]
結局上の話は Funcref だけ参照するようになりました（詳しくは #504 を見てください）。

**Comment by tyru** [comment]
タイトルの結論は出たのでクローズします。
皆さんありがとうございました！
