### ISSUE TITLE
vital.vim開発者会議2017-06

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#512]
というのを考えてみました。
https://connpass.com/event/57862/

## 背景

meguro.vimでvitalの既存のpullreqのreviewしたり、こんな機能欲しいねとか、neovimサポートどうするかとかの議論を行った。最終的な意思決定はgithub上だが、しかしその前に雑にSOUDANできる環境があると物事が一気にすすんで便利ということに気づく。

## 参加形態

* 休日は僕が忙しいので平日夜を想定
* 東京都恵比寿近くで普段仕事してる人は、恵比寿のfablic.vim社に集まって開催
* そうでない人はリモートで参加。google hangoutとかで画面共有する感じ
    * リモート参加の人数が多いと難易度高まるので、高々2名くらいを想定

## その他

fablic社側から食事だせれそう。

**Comment by aiya000** [comment]
ピッザ欲しいけどおそらくリモート参加になりそう……

**Comment by ujihisa** [comment]
遅くなったけど https://connpass.com/event/57862/ に詳細記述しました。 :pizza: 食べましょう。

**Comment by aiya000** [comment]
Agendaのスタイルが崩れてる気がw  
僕も実地に行ける！

**Comment by ujihisa** [comment]
おっとthx! 修正しました。

もし興味あれば早めにきてくれれば社内案内とかもできます (vital.vim開発者会議する場所と同じ大部屋だけど、別エリア)

**Comment by thinca** [comment]
無事開催されて終了しました。第2回期待。
