### ISSUE TITLE
Remove --rubyinterp　とか

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/vital.vim#534]
1. `has('ruby')/has('perl')` なコードはない
2. 使ってないのに https://travis-ci.org/vim-jp/vital.vim/jobs/256352309#L1641 みたいに設定不備などで ruby 関連で落ちるの辛い

の二点から `--rubyinterp` とか `--perliterp` とか消したい。

面倒臭すぎて https://github.com/vim-jp/vital.vim/pull/513 では消したけど、一応別枠で確認を取りたい。

**Comment by tyru** [comment]
:+1:
