### ISSUE TITLE
consider tagging git releases for packaging

### ISSUE THREAD

**Issue by anthraxx** [vim-jp/vital.vim#556]
Hey,
i would appreciate if you could consider tagging git releases for now (and in the future). This would help it to package this plugin into distros and possibly other sources.

**Comment by tyru** [comment]
Hi,
Thanks for suggestion.

This library installs by using `:Vitalize` itself with current version of the commit hash.
So I personally think it's not necessary.

What use are you thinking?

**Comment by anthraxx** [comment]
I think it still can't hurt as other plugins depend on this, which you may want to install as a distro package. therefor this is a dependency that needs to be satisfied during installation time rather then runtime of a given user.

**Comment by tyru** [comment]
`:Vitalize` **copies** vital.vim source files under `autoload/vital/` directory of  the plugin repository which depend on vital.vim.
so the dependency is satisfied during installation time.
Please see [README](https://github.com/vim-jp/vital.vim#lets-get-started).

**Comment by anthraxx** [comment]
thats certainly not how you package dependencies for a distribution and you certainly don't call :Vitalize vor every vim plugin that depends on this, this results in all such plugins copying the same file to autoload leading to a file clash.

**Comment by k-takata** [comment]
Every plugin that uses vital.vim must bundle a copy of it, and `:Vitalize` does it automatically.
Vital.vim is not intended to be used without vitalizing. Moreover, every vitalized vital.vim does not conflict with each other.

**Comment by anthraxx** [comment]
You are missing the point of packaging, vitalizing it installs it in a unique location which is the same for independent packages using vital. therefor conflicting on package manager level when installing, which denies doing so.
Never mind I solve that myself, don't feel like anyone wants to accept this use case.  Shrug.

**Comment by k-takata** [comment]
Creating a package of vital.vim itself is not expected.

**Comment by anthraxx** [comment]
All I asked for is a git tag.
Unfortunately you don't even seem to realize the implications when packaging a plugin that uses vital into /usr/share/vim/vimfiles. Sorry to say that this is reality, expected or not doesn't change this.

**Comment by tyru** [comment]
For now, vital.vim project does not plan to release periodically, and also create a package for distro like Debian, Arch, and so on.

And if you still want vital.vim to support this, please provide more information like:
* What distro are you using?
* What package manager are you using?

**Comment by anthraxx** [comment]
@tyru i see, thanks anyway... no need to create packages for Arch, thats what i'm doing right now in order to make multiple plugins using vital work as Arch package... package manager is pacman :yum:

**Comment by lambdalisue** [comment]
@anthraxx 

You probably misunderstood this library.

Any plugin using vital.vim **DOES NOT REQUIRE** vital.vim itself because files are injected into each plugins' `autoload/vital/_PLUGIN_NAME` directory by **plugin developers** rather than end users.

For example, [gina.vim](https://github.com/lambdalisue/gina.vim) is using vital.vim's [`vital.vim/autoload/vital/__vital__/Data/String.vim`](https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__vital__/Data/String.vim) but that file is copied into gina's [`gina.vim/autoload/vital/_gina/Data/String.vim`](https://github.com/lambdalisue/gina.vim/blob/master/autoload/vital/_gina/Data/String.vim) in **development phase** (so that the file exists in gina.vim's repository) and gina refer that file rather than the original one.

That's why we don't think any distribution package for vital.vim is required for end users.

**Comment by anthraxx** [comment]
@lambdalisue I'm pretty much aware what you are suggesting and what you planned vital to behave... i fully get that. You probably misunderstood the problem so i will repeat it in a verbose way.

While this is the way it can sit in a plugins development environment, this is not a way it can get distributed as a package into the distro.

example:
you package gina as a distro package, therefor its autoload files go do `/usr/share/vim/vimfiles/autoload` untimely adding a `/usr/share/vim/vimfiles/autoload/vital/__vital__`
now i package easymotion, which also has a `easymotion.vim/autoload/vital` so the distro package ends up with a file `/usr/share/vim/vimfiles/autoload/vital/__vital__` which will conflict a gina distro package for named files.
This works super well if a user manages its plugins from a user runtime via f.e. vundle and stuff gets installed into his home directory and stuff... but this does not work so nice for distro packaged vim plugins because of the above reasons.

**Comment by lambdalisue** [comment]
No. The path is different.

In gina, the `Data/String.vim` is in `/usr/share/vim/vimfiles/autoload/vital/_gina/Data/String.vim`.
In easymotion, the `Data/String.vim` is in `/usr/share/vim/vimfiles/autoload/vital/_easymotion/Data/String.vim`.

**Comment by anthraxx** [comment]
https://github.com/easymotion/vim-easymotion/blob/master/autoload/vital.vim

**Comment by lambdalisue** [comment]
That was used previously but as you said, it has some problem so we fixed. It is easymotion's problem.

For example, gina.vim does not have it because it use the latest one.

https://github.com/lambdalisue/gina.vim/tree/master/autoload/vital

**Comment by lambdalisue** [comment]
Oops sorry. Wrong one. Yes gina has it.

**Comment by lambdalisue** [comment]
Or you are saying that distro package system cannot overwrite that file? In that case, I think it's worth to discuss removing that file (`autoload/vital.vim`)

**Comment by tyru** [comment]
Ah i see.

@anthraxx `autoload/vital.vim` is a old file.
You can report the bug to the plugin author if the file exists :)
Now vital.vim solved the problem so unifying plugins' files to one path must not conflict if all plugins use the latest vital.

**Comment by anthraxx** [comment]
Yes, conflicting files are the problem. 
That sounds like a plan, guess will take a while until such projects also create a new release but time will solve that 😁 will file an update request against easymotion

**Comment by tyru** [comment]
> will file an update request against easymotion

👍 

However, I misunderstood current implementation of vitalizer.
Currently `:Vitalize` appears to install `autoload/vital.vim` yet.
I don't remember why this file is created but @thinca or @haya14busa should know the reason.
(as @lambdalisue said, this is compatibility reason?)

**Comment by tyru** [comment]
(oops, I was confused, rewrote my comment...)

**Comment by tyru** [comment]
@thinca seems to be fixing the problem `autoload/vital.vim` is created. #558
