### ISSUE TITLE
vital.vim 開発者会議 2018-03 告知

### ISSUE THREAD

**Issue by thinca** [vim-jp/vital.vim#577]
今週の木曜日である 2018-03-01 に、vital.vim 開発者会議が行われます。

https://fablicvim.connpass.com/event/74842/

開催については主に Slack の vim-jp チーム内にある `#vital-dev` チャンネルで話し合われていましたが、ここを参照していない人もいると思うので、直前にはなってしまいましたが告知のために Issue を立てました。
想定されている議題は以下のような感じです(他に議題あれば今から提案してもらっても OK)

- neovim support の方針について (関連: #572)
- vitalizer分離 (#568)
- reorganize module namespace (#563)

開発者会議となっていますが、どなたでも参加可能です。vital.vim に興味があってこれから貢献してみたいと言う方でも大丈夫です。参加希望の方は上記の connpass ページから申し込んでください。

**Comment by ujihisa** [comment]
あと豪華ではないけど食事もでます!

**Comment by lambdalisue** [comment]
https://github.com/vim-jp/vital.vim/commit/8028517d7d7a8bdbee500cf188ca46a488715961

**Comment by thinca** [comment]
参加者

- @lambdalisue 
- @thinca
- @tyru 
- @ujihisa

**Comment by thinca** [comment]
実際使うかわからないけど、取れなくなる前に作ってしまえということで勢いで org を作った。
https://github.com/vim-vital

**Comment by lambdalisue** [comment]
Neovim はゆるくサポートする。

**Comment by tyru** [comment]
比較演算子は `==#`, `!=#` の代わりに `is#`, `isnot#` を使った方がいいのでは（と言った）（決定事項ではない）
関連: https://github.com/Kuniwak/vint/issues/233

**Comment by tyru** [comment]
ちなみにエレベーターでちらっと話した Vim 8 channel で HTTP を喋るやつはこの Request モジュールです。 `Request.get(url)` とかやって使います。
https://github.com/tyru/vital-sunaba/tree/8e51ce43d9eece2faba5d611d74e32285b374cbb/autoload/vital/__sunaba__
サンプルコード
https://github.com/tyru/vital-sunaba/blob/8e51ce43d9eece2faba5d611d74e32285b374cbb/examples/WebSocket.vim#L19-L28

同じディレクトリにある `Template`, `WebSocket` モジュールは
* Template: Go の text/template の Vim script 移植版 (予定)
  * トークナイズ、パースはそれなりに真面目にやってるので結構遅いと思いますが、一旦パースして Funcref にコンパイルした後は速くなる想定
* WebSocket: Vim script 実装 (予定)
  * ヌルバイトを扱えない事には外部インターフェースを使うしかない（めんどい）でストップ中
  * 関連: https://github.com/vim-jp/issues/issues/1148

想定している使い方は以下のサンプルコード参照
https://github.com/tyru/vital-sunaba/tree/8e51ce43d9eece2faba5d611d74e32285b374cbb/examples

**Comment by thinca** [comment]
会は終了したので本 Issue は閉じます。
追加タスク等ある場合は Issue を作るのが良さそう。(既存 Issue の延長のみで追加はたぶんない気がする)
