### ISSUE TITLE
[RFC] Async.Promise 改定案

### ISSUE THREAD

**Issue by lambdalisue** [vim-jp/vital.vim#590]
ガチで使っていると Vim script 的に使いにくい点がいくつか出てきたので改定したいなという相談です。
以下のように別のモジュールとして開発しようと思っていましたが `Async.Promise` を完全に TC39 互換にする必要性は無いので提案します。
一つ目の任意個数の引数以外、すでに実装・ドキュメント・テストすべて揃っています。

https://github.com/lambdalisue/vital-Whisky/blob/master/autoload/vital/__vital__/Async/Promise/Util.vim
https://github.com/lambdalisue/vital-Whisky/blob/master/doc/Vital/Async/Promise/Util.txt
https://github.com/lambdalisue/vital-Whisky/blob/master/test/Async/Promise/Util.vimspec

### resolve/reject で任意個数の引数を受け取れるようにする

今は一つの値しかやり取り出来ないが、任意個数の値を渡したい。
これによって各引数に意味を持たせられるのでコールバックがわかりやすくなる。

```vim
" Actual
function! s:on_then(result) abort
  let [result, context] = a:result
  call setbufline(context.bufnr, result)
endfunction

call Promise.resolve([result, context]).then(funcref('s:on_then'))

" Ideal
function! s:on_then(result, context) abort
  call setbufline(a:context.bufnr, a:result)
endfunction

call Promise.resolve(result, context).then(funcref('s:on_then'))
```

### 同期的に状態・値を取得するヘルパー関数の追加

完全に非同期だと使いにくいため以下のような関数を `Promise.state({promise})`, `Promise.result({promise})` として追加したい。
特にテスト等を書いたり、一部同期的に動作させる場合に便利。

```vim
let s:STATES = ['pending', 'fulfilled', 'rejected']
function! s:state(promise) abort
  return s:STATES[a:promise._state]
endfunction

function! s:result(promise) abort
  return a:promise._result
endfunction
```

### 同期待ちをするヘルパー関数の追加

同期待ちしたいことも多いので追加したい。

```vim
function! s:wait(promise, ...) abort
  let t = a:0 ? (a:1 / 1000) : v:null
  let s = reltime()
  while a:promise._state is# s:PENDING
        \ && (t is# v:null || reltimefloat(reltime(s)) < t)
    sleep 10m
  endwhile
  return s:state(a:promise)
endfunction
```

**Comment by ujihisa** [comment]
(細かいとこ一点だけ: 同期的な処理をするやつはユーザにとって不便であくまでテスト・開発時のものであることを強調するため、関数名を長くする (使ってるとすぐにわかるようにする) のがよさそうです。

* `Promise.result({promise})` -> `Promise.result_blocking({promise})`
* `Promise.wait({promise}, ...)` -> `Promise.wait_blocking({promise}, ...)`
)

**Comment by tyru** [comment]
> 以下のように別のモジュールとして開発しようと思っていましたが Async.Promise を完全に TC39 互換にする必要性は無いので提案します。

うーん多分無いかもしれませんが、今後 `Promise.resolve()` に新しい引数が追加されたとしたら Vital.Async.Promise は互換じゃなくなってしまうので、ECMAScript 互換は大きい利点なんじゃないですかね？
正直別のモジュールにヘルパー関数定義してやれるなら先方互換性を壊すほどのメリットがあるかなーとちょっと思いました。

**Comment by lambdalisue** [comment]
> 同期的な処理をするやつはユーザにとって不便であくまでテスト・開発時のものであることを強調するため

ここなんですが Vim script である以上、不必要に非同期を厳守する必要が無いと考えています。なので  関数名を長くすることで利便性を下げる必要はないかなと思います。

**Comment by lambdalisue** [comment]
とりあえず今の意見をまとめると

1. resolve/reject で任意個数の引数を受け取れるようにする -> 諦める
2. 同期的に状態・値を取得するヘルパー関数の追加 -> `state_blocking`, `result_blocking`
3. 同期待ちをするヘルパー関数の追加 -> `wait_blocking`

とすればお二方の理想の形でイケるかな（`state_blocking` みたいな長い関数は TC39 とかぶらないと仮定）。

**Comment by tyru** [comment]
> 1\. resolve/reject で任意個数の引数を受け取れるようにする -> 諦める

(基本的には author の @rhysd さんの意見を尊重したいので、@rhysd さん待ちです)

**Comment by rhysd** [comment]
すみません，今日は検討する時間無さそうなので明日読んで考えてみます

**Comment by rhysd** [comment]
@lambdalisue 

提案ありがとうございます．
僕も基本的にこの案の方針には賛成です．提案いただいたインターフェースはすべて現状の `Vital.Async.Promise` のインターフェースを破壊的に変更せずに実装できますよね？それであれば，ES6 Promise との互換性は壊れません（semver で言うところの major version は変更しない，ですよね？）さらに，実際の使用経験に基づいて提案いただいているので，内容的にも reasonable だと思います（JS なら引数の destructuring などで1引数でもなんとかなりますが，Vim script にはないので引数で一旦受けてからその中の値を取る必要があって二度手間になります．

ES6 Promise 互換にこだわっているのは，ES6 Promise を触ったことがある人が Vim script でも同じ知識＆感覚でコードを書けるようにしたいためです．なので，ES6 Promise の機能を壊さない範囲での追加は歓迎です．（将来的に壊れるかも？という話はありますが，そこまで言うと何もできなくなるので，壊れた時にその都度議論するで良いと思います）キャンセル周りとかコンフリクトする機能が近い将来に入る可能性が高いものについては様子を見たい気持ちもありますが…今回の提案には含まれていないと思うので問題ないです．

### resolve/reject で任意個数の引数を受け取れるようにする

これはやってしまって良いように思います．既存のインターフェースが壊れないかつ明確なメリットがあるためです．将来的に ES6 に変更があり，例えば `resolve` の引数に別の引数が入ったときには `Vital.Async.Promise` の互換性を崩す形で解決すれば良いと思います．

### 同期的に状態・値を取得するヘルパー関数の追加

すみません，下記の説明部分がよく分からなかったので説明いただいても良いでしょうか？

> 同期的に状態・値を取得するヘルパー関数の追加

少なくとも `result` 自体は同期的に値を取得していません．やっているのは nonblocking で値を取ってみる（ただしまだ値が無い場合は `null` になる）です．

あと，Promise のステートは ES6 では明確なメリットがあってあえて取れないインターフェースになっているので，`state` はそれを超えるメリットが無い限り実装しないほうが良いと思います．`p._state` みたいに undocumented な裏仕様として使ってもらうぐらいのほうが良いかなと（今の実装）

### 同期待ちをするヘルパー関数の追加

これについても明確なユースケースがほしいです．同期待ちをやりたい場合は待たせたい値 `v` を `Promise.resolve(v)` で Promise オブジェクトをつくり，`Promise.all` で待ち合わせをする（つまり全て非同期側に寄せる）のが JS だと一般的だと思いますが，それだと Vim script では取り回しづらいということかなーとは察するのですが．

**Comment by lambdalisue** [comment]
## 同期的に状態・値を取得するヘルパー関数の追加

「同期的に取得」というのが語弊がありました、正しくは「同期的に現在の状態を取得」です。そのため提示したコードでは `_state` 等の内部変数の値を返す関数としています。
裏仕様の場合リファクタリング等によって動かなくなる可能性が怖いため、明示的に仕様にしてはどうか？という提案でした。加えて関数にすることで、取得限定にすることができます。

実際に必要になった場面は主にテストです。

https://github.com/lambdalisue/vital-Whisky/blob/master/test/Async/Promise/Util.vimspec#L51-L56

上記のように「一定の条件が満たされることで Promise が確定する」というテストを書く場合に同期的に現在の状態が取得できないと Vim script ではかなりテストを書くのが難しくなります。

ちなみに僕は TypeScript (JavaScript) であれば以下のように仮想的な同期処理っぽく書きますが、これは Vim script だと無理でしょう。

```typescript
// 特定の Promise の状態を返す Promise を返すヘルパー関数
// ちなみに Async.Promise の Promise.race だと比較順番の関係か以下と同等のコードが動きませんでした。
// 詳細を見ていないのでバグ報告はしていませんが、念のためお知らせ。
function state(p: Promise<any>): Promise<'pending' | 'fulfilled' | 'rejected'> {
  const t = {};
  return Promise.race([p, t]).then(
    (v: any) => (v === t) ? 'pending' : 'fulfilled',
    () => 'rejected',
  ) as Promise<'pending' | 'fulfilled' | 'rejected'>;
}

p = Promise.resolve();
// p が fulfilled かテスト
await expect(state(p)).resolve.toEqual('fulfilled')
```

また後述しますが同期待ちをするヘルパー関数が出てきた段階で同期的に現在の状態を取得する方法というのは必要になります。

## 同期待ちをするヘルパー関数の追加

> それだと Vim script では取り回しづらいということかなーとは察するのですが．

そのとおりですね。今回はテスト用に必要になりましたが、実ユースケースで言えば、例えば補間関数やステータスライン用の関数等が考えられます。
もちろん Producer/Consumer モデル的に以下のように一時変数を媒介すれば可能ですが、この場合即時性が犠牲になってしまいます。
また「同期的にやるのに Promise 不要じゃね？」はそのとおりですが Promise を同期的に使う手段があれば非同期・同期の実装を分ける必要がなく便利です（`job_start` と `system()` の差異とか色々あるので）。
そのため「Promise を使うけど同期的にやりたい」という要望はかならずあると思います。

### Git のブランチを表示するステータスライン例

#### 非同期で頑張る場合

```vim
let s:current_branch = '?'
let s:current_promise = v:null

function! s:on_then(result) abort
  let s:current_branch = a:result
  let s:current_promise = v:null
endfunction

function! s:execute(args) abort
  return s:Promise.new({ r -> s:Job.start(a:args, { ... }) })
endfunction

function! GitBranch() abort
  if s:current_promise is# v:null
    let s:current_promise = s:execute(['git', 'branch'])
          \.then(funcref('s:on_then'))
  endif
  return s:current_branch
endfunction

set statusline=%{GitBranch()}
```

#### Promise.wait/Promise.result がある場合
```vim
function! s:execute(args) abort
  return s:Promise.new({ r -> s:Job.start(a:args, { ... }) })
endfunction

function! GitBranch() abort
  let p = s:execute(['git', 'branch'])
  call s:Promise.wait(p)
  return s:Promise.result(p)
endfunction

set statusline=%{GitBranch()}
```

**Comment by lambdalisue** [comment]
ちなみに外部から状態を変更可能な Deferred タイプ（jQuery の Deferred, Python の Future, 古い JS の Promise.Deffered 等の総称として言っています）があると、さらにテストを書くのが楽になりますが、これは外部モジュールで良いと判断したため今回の提案からは外しました。

https://github.com/lambdalisue/vital-Whisky/blob/master/test/Async/Promise/Deferred.vimspec

**Comment by rhysd** [comment]
非同期な処理のテストが書きにくいのは単体テストフレームワークが対応すれば解決する気がします（CC: @thinca）が，需要についてもう少し質問させてください．
テスト目的でほしいとのことなのですが，JS で Promise を使っていると Promise の状態自体を知りたいということは僕は無いのですが，状態を知りたいのはもう少し具体的にどういうテストを書いているときでしょうか？
非同期処理の結果の値をテストしたいだけなら `wait()` があれば足りるかなと思いました．

**Comment by tyru** [comment]
> テスト目的でほしい

:+1: (via https://twitter.com/_tyru_/status/1008523066886901760)

(上では反対してたので改めて)

**Comment by lambdalisue** [comment]
> 非同期な処理のテストが書きにくいのは単体テストフレームワークが対応すれば解決する気がします（CC: @thinca）が，需要についてもう少し質問させてください．

テストフレームワークが対応すれば解決という点は同意です。
ただ、そもそも Vim script 自体に Promise が存在していなかったこともあり、テストフレームワークでの対応は非現実的だと考えています（themis だけ対応するというならば現実的ですが Promise の概念とテストフレームワークは直行するべきという立ち位置です）。

> テスト目的でほしいとのことなのですが，JS で Promise を使っていると Promise の状態自体を知りたいということは僕は無いのですが，状態を知りたいのはもう少し具体的にどういうテストを書いているときでしょうか？（示していただいた例は Promise のユーティリティ自体のテストなので，アプリケーションコードのテストでどう使われるのかあまり想像できないなぁと）
> 非同期処理の結果の値をテストしたいだけなら wait() があれば足りるかなと思いました．

以下は「外部処理の出力を全て大文字にして返す非同期関数。ただし処理中は `statusline` が `'Waiting...'` となる」という機能を想定しています。

```vim
function! test#start() abort
  let spinner = s:start_spinner()

  function! s:on_then(result) abort closure
    call spinner.stop()
    return toupper(a:result)
  endfunction

  return s:start_process()
        \.then(funcref('s:on_then'))
endfunction

" ランダム時間後に 'Hello' を返す Promise （外部処理を模倣）
function! s:start_process() abort
  let interval = s:Random.next()
  return s:Promise.new({ resolve -> timer_start(interval, { -> resolve('Hello') }) })
endfunction

" 処理中を表す Spinner を返す関数
" 簡略化のため statusline を固定文字列に書き換えるだけ
function! s:start_spinner() abort
  let statusline_saved = &statusline
  let &statusline = 'Waiting...'

  function! s:on_stop() abort closure
    let &statusline = statusline_saved
  endfunction

  return {
        \ 'stop': funcref('s:on_stop')
        \}
endfunction
```

上記の関数に関して、以下の点に関してテストしたいと仮定します。
なお「外部処理」自体に関しては別枠で担保されており、ここではテスト不要と仮定しています。

1. 外部処理実行中は `statusline` が適切に書き換えられているか？
2. 外部処理が完了したら `statusline` が戻っているか？
3. 外部処理の出力結果が正しく正規化（ここでは大文字化）されているか？

以上を踏まえると、以下のようなテストが想定できます。

```vim
" 本物の処理を使うとタイミングが一意に定まらないため
" s:ScriptLocal にて外部処理部分を s:Deffered に書き換えて任意タイミングで状態を変更可能にする
let s:sf = s:ScriptLocal.sfuncs('.../autoload/test.vim')
function! s:sf.start_process() abort
  return s:Deffered.new()
endfunction

" テスト
function! s:test() abort
  let statusline_saved = &statusline
  " 処理の開始 (返り値の promise は Deffered インスタンス)
  let promise = test#start()
  " この段階では処理中なことをテストする
  " 上記は簡単な関数なので自明ですが、複雑になると
  " この段階で 'pending' ではなくなっているかもしれない
  assert s:Promise.state(promise) ==# 'pending'
  " 処理中のため statuslien が 'Waiting...' になっているはず
  assert &statusline ==# 'Waiting...'
  " 処理が終わったことを模倣する (Deffered だから可能)
  call promise.resolve('Hello')
  " 処理が終わるまで待つ (resolve は非同期的なため通常必要)
  " 念のため 10 秒でタイム・アウトするように
  call s:Promise.wait(promise, 10000)
  " 処理が完了したことをテストする
  " 上記は簡単な関数なので自明ですが、複雑になると
  " この段階で 'fulfilled' ではないかもしれない
  assert s:Promise.state(promise) ==# 'fulfilled'
  " statusline が戻っていることをテスト
  assert &statusline ==# statusline_saved
  " 正しい値が返ってくることをテスト
  assert s:Promise.result(promise) ==# 'HELLLO'
endfunction
```

> あと，上でも少し話が出ていますが，テスト用途であればアプリケーションコード側での仕様は非推奨のはずなので，あまりカジュアルな名前は避けたいです．個人的には採用するとしても

これは後述する `wait()` の仕様によりアプリケーションコードでもカジュアルに使う可能性があると思っています。

> 実装についてもう少し詰めたいのですが，下記について意見を伺いたいです．

おそらく `wait()` の仕様に対する認識ズレがあると思っています。
僕は定義的には `wait(p: Promise, timeout?: number): 'fulfilled' | 'rejected' | 'pending'` であるべきかなと思います。
`wait()` が状態を返すことで返り値の型が定まるのと timeout の際に `'pending'` が返るため以下のようにタイムアウト判定が簡単になります。

```vim
" 一定時間ごとに Waiting... を echo して動いていることを表現する例
while True
  if s:Promise.wait(p, 1000) !=# 'pending'
    break
  endif
  echo 'Waiting...'
endwhile
echo "Done" . s:Promise.result(p)
```

上記のような定義であれば `result()` 関数はアプリケーションコードでも必ず利用する関数となります。
そのため `result_nonblock()` のように使用されないようにするという意図を持って長い名前にするのは懐疑的です。
ただ `result()` 以外にシンプルで使いやすい名前があればそちらでも構いません。

なお `state()` に関してはオマケ感があるため、明確にドキュメント化されていて予期しない変更が無いのであれば、煮るなり焼くなり好きにしようという感じです。

**Comment by lambdalisue** [comment]
オマケと言いましたが wait にて内部状態をユーザーに提示するならば state 関数もカジュアルに使えないと仕様的に変ですね。前言撤回します

**Comment by lambdalisue** [comment]
代替案としては wait は reject/timeout で例外を投げるですが例外クラス的なのが無いので例外文字列の比較が必須になり、逆に面倒臭そうです。

**Comment by rhysd** [comment]
> おそらく wait() の仕様に対する認識ズレがあると思っています。

すみません，1点勘違いしていたのですが，@lambdalisue さん案だと `wait()` は状態を返すのですね．私は値を返すのだと勘違いしていました．僕は値を返したほうが良い（理由は `state()` を実装すべきでないのと同じ）と思うのですが，どうでしょう？

```vim
let p = Promise.resolve({res -> s:do_jikan_kakaru_shori(res)})

" タイムアウト付きで p の resolve を待ち，結果を ret に格納．reject される or タイムアウトしたら例外が飛ぶ
let ret = Promise.wait(p, 1000)
```

ただしこれにも2点問題があります．

- `catch()` では例外オブジェクトが渡ってきますが，`wait()` が例外を投げるとした場合，文字列しか投げられない．ここは `let [result, ok] = Promise.wait(p, 1000)` のように resolve されたかどうかを第2戻り値で返すのも良いかなと思います
- 例外のチェックが面倒なのはそうですね…

使用例の例示ありがとうございます．
ただ，やはり状態を取るべきではないように思います．例示いただいたテストでいくと，

```vim
" テスト
function! s:test() abort
  let statusline_saved = &statusline
  " 処理の開始 (返り値の promise は Deffered インスタンス)
  let promise = test#start()

  " この時点で pending でなくてもそれはエラーではないので fail
  " にすべきではない気がします．一瞬で終わるかしばらくかかるか分からない処理を
  " テストする場合，その両方の場合をテストケース内で考慮すべきだと思います
  " もし assert s:Promise.state(promise) ==# 'pending' が 99.99% 起き得ないことを
  " チェックしているのであれば，そのチェックは要らないです．
  " 最悪起きても下の &statusline のチェックでテストが落ちます．
  if statusline !=# 'Waiting'
      " TODO: statusline が結果を正しく表示していることのチェック
      return
  endif

  " 処理中のため statuslien が 'Waiting...' になっているはず
  assert &statusline ==# 'Waiting...'

  " 処理が終わったことを模倣する (Deffered だから可能)
  call promise.resolve('Hello')

  " 例外が飛んでいない（正常に処理が完了した）ことをチェックする
  NoThrow let result = s:Promise.wait(promise, 10000)

  " 例外が飛ばなかったので，ここで promise の状態は fulfill に確定する
  " のでチェックする必要はなし

  " 後処理が正しく行われていることをチェック
  assert &statusline ==# statusline_saved

  " 正しい値が返ってくることをテスト
  assert result ==# 'HELLLO'
endfunction
```

全体的に，@lambdalisue さんは実行の状態をテストしようとされていますが，実際には，アプリケーションの内部状態である実行状態ではなく，外（ユーザ）から見えるアプリケーションの振る舞いに対してテストを書くべきだと思います．

> ただ、そもそも Vim script 自体に Promise が存在していなかったこともあり、テストフレームワークでの対応は非現実的だと考えています

はい，私も直対応というよりは Mocha の `done` コールバックみたいなのをイメージしていました．いずれにせよフレームワークの対応前提で話を進めるのもアレなのでここではそれは無い前提で良いと思います．

**Comment by rhysd** [comment]
> while True
>   if s:Promise.wait(p, 1000) !=# 'pending'
>     break
>   endif
>   echo 'Waiting...'
> endwhile
> echo "Done" . s:Promise.result(p)

うーんこれについては `timer_start()` で1秒毎に `:echo` する処理をつくっておき，Promise 側の処理が完了した時にフラグを立ててタイマーはそのフラグを見て1行ごとの echo をやめるというのが自然な実装だと思います．

**Comment by lambdalisue** [comment]
あー「仕様に存在しない `state()` を欲しいと考える理由」ってのを自分自身が勘違いしていたようです。当初は「Vim script の表現力的に非同期に拘りすぎる必要がない」という点と「現在の Promise の状態が欲しかったことがある」という点から推奨していましたが、後者は Python における完了・失敗・キャンセル状態をチェックする記憶が混ざり込んでいた気がします。自分的にも提示している例が良くないなーとは思っていましたが、よくよく考えてみると TypeScript で書いてるプロジェクトだとそもそも状態チェックは一切していませんでした。

そのため @rhysd さんの以下の仕様に全面的に賛成いたします

1. `Promise.result()` と `Promise.state()` は一切実装しない
    - 外部から状態を変更可能な `Deffered` では必要かもしれないが `Promise` だと不要
2. `Promise.wait()` は結果を返す or 例外を投げる
    - タイムアウト時に例外を投げる（固定値）

**Comment by lambdalisue** [comment]
実装開始フェーズになったと思うので、こちらはクローズします。
以後は https://github.com/vim-jp/vital.vim/pull/598 で
