### ISSUE TITLE
Ensure Data.List functions are nondestructive

### ISSUE THREAD

**Issue by tyru** [vim-jp/vital.vim#592]
via https://github.com/vim-jp/vital.vim/pull/511#issuecomment-396419319 (thanks @Milly)

* Remove unnecessary `copy()` from test files
* Add tests to check if functions are nondestructive
* Remove unnecessary `copy()` from document
* Note all functions are nondestructive in the document
  * `Data.List.uniq()`, `uniq_by()` are noted already
  * Is it enough to note all functions are nondestructive in introduction section?

**Comment by ujihisa** [comment]
Since existing Data.List functions are not necessarily nondestructive, I'll clarify destructive/nondestructive for each functions in the documentation, as the first step.

**Comment by ujihisa** [comment]
According to the comment we aren't changing Data.List entirely to non-destructive. Since all the functions with `{list}` argument clearly mention if they are destructive or non-destructive, I close this now.
