### ISSUE TITLE
CIs are flaky

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#604]
![](https://i.gyazo.com/ee73272e786996112dec77d302bc6db3.png)

That's a typical case. Restarting jobs sometimes solve, but that's not a solution but just a workaround.

**Comment by tyru** [comment]
via https://github.com/vim-jp/vital.vim/pull/602#issuecomment-406537940

It is failing by #598 changes.
I agree "rerun is just a workaround."
But I have no better idea than just increasing the ranges.

**Comment by ujihisa** [comment]
> （マージンもっと取った方が良さそう？ cc: @lambdalisue）
> https://github.com/vim-jp/vital.vim/pull/602

I guess we can introduce retries in the test code, only for some unstable test cases, such as Promise module

**Comment by ujihisa** [comment]
Thanks to @ichizok 's couple of pull requests, CIs are finally stable.

**Comment by ujihisa** [comment]
TODO: enable OSX Async.Promise tests again
