### ISSUE TITLE
add support for callbag/rx observables

### ISSUE THREAD

**Issue by prabirshrestha** [vim-jp/vital.vim#622]
Specification: https://github.com/callbag/callbag
Would be good to have something like https://github.com/staltz/callbag-basics in vital.vim.

```javascript
pipe(
  interval(1000),
  map(x => x + 1),
  filter(x => x % 2),
  take(5),
  forEach(x => console.log(x))
)
```

This will make it very easy to also support Rx on top of callbags. Example: https://github.com/staltz/callbag-pseudo-rxjs

```javascript
Observable.interval(1000)
  .map(x => x + 1)
  .filter(x => x % 2)
  .take(5)
  .subscribe({
    next: x => console.log(x),
    error: e => {},
    complete: () => {}
  });
```

I'm mainly interested in implementing more complex async patterns such as this in vimscript. https://medium.com/@rachel.poulos/wreck-the-web-with-observables-how-to-make-an-autocomplete-search-with-rxjs-bd588ad91b1b

```javascript
let input$ = fromEvent(searchBox, 'input')
  .pipe(
    map(e => e.target.value),
    debounceTime(250),
    filter(query => query.length >= 2 || query.length === 0),
    distinctUntilChanged(), 
    switchMap(value => value ?
      from(searchGithub(value)) : from(Promise.resolve({items: []}))
    )
  );
```

Note: RxJS7 is getting rewritten using callbags. https://twitter.com/ladyleet/status/1058035320611057670

**Comment by ujihisa** [comment]
MEMO: @lambdalisue's https://github.com/lambdalisue/vital-Whisky has `Observable` as a vital external module

**Comment by prabirshrestha** [comment]
I did see that. Looks great. Any reason why it isn't part of vital.vim repo?

Here was another partial implementation of Rx I found on github for vim. https://github.com/Krakarn/krakarn-vim-core/blob/master/autoload/krakarn/utils/observable.vim

**Comment by lambdalisue** [comment]
> I did see that. Looks great. Any reason why it isn't part of vital.vim repo?

1. vital-Whisky is kind my playground and modules are experimental
2. vital.vim itself does not run unittests on Neovim but vital-Whisky

**Comment by prabirshrestha** [comment]
started initial implementation of callbag at https://github.com/prabirshrestha/rx.vim

```viml
let s:i = 0
function! s:next(cb) abort
    echom s:i
    let s:i = s:i + 1
endfunction

function! rx#callbag#demo() abort
    let l:res = rx#callbag#pipe(
        \ rx#callbag#interval(1000),
        \ rx#callbag#take(3),
        \ rx#callbag#forEach(function('s:next')),
        \ )
    return l:res
endfunction
```

**Comment by prabirshrestha** [comment]
[callbag.vim](https://github.com/prabirshrestha/callbag.vim) now contains lot more operators and features. I'm planning to start using it in [vim-lsp](https://github.com/prabirshrestha/vim-lsp) for some of the features. Here is a PR that uses callbags https://github.com/prabirshrestha/vim-lsp/pull/845.

It can be embedded using `:CallbagEmbed path=./autoload/myplugin/callbag.vim namespace=myplugin#callbag` so anyone should be able to use it easily.
