### ISSUE TITLE
Update: Lingr notification is not unnecessary because It has already been discontinued.

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vital.vim#654]
https://github.com/vim-jp/vital.vim/blob/7fe2baf0c8c9f280a586ba087e24b2dfd9c9a8f3/.appveyor.yml#L43-L47

---

タイトルがちょっと複雑になりましたが、上記設定が不要なら削除かslack用に更新したほうがいいのではないか、と思うので。

もし、まだlingr側で通知を見ているならば別ですが、先日vim-jpトップからも記載を消していますし...

**Comment by mattn** [comment]
要らないですね。いい気付き。

**Comment by tsuyoshicho** [comment]
というか、herokuapp、止めてもいいかもしれない(アクセスアタックされるかもしれないので)

**Comment by raa0121** [comment]
あー これ私管轄のBotですね

**Comment by ujihisa** [comment]
Fixed at bde0ad0a9985ef8b7131f4b8b02d64636bb66c30
