### ISSUE TITLE
Question: Random module policy

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vital.vim#657]
日本語ですみません。

`Random`自体の挙動について確認したいです。

現在、`Random`の`Generator`を作ろうとしています。
(名前としては`Random.System`になりそうです。)

用途としては、やや特殊で、意図して入れない限りは使わないほうが良いものです。
(これとは別ですが、今後テスト用に乱数ではなく固定値を返すようなものも作りたいとも考えています。が直接関係無いので置いておきます)

やや特殊なので

- `Random`の`Generator`なので、名前指定での利用も考えると`Random.*`として入れたい
- だけどそのままデフォルトの選択肢にはなってほしくない

というのがあります。

そのまま`Vitalize`で`+Random`とするとメルセンヌツイスタ(`Mt19937ar.vim`)がはいります。
疑問を確認するために、`Asystem`として確認した場合は`Asystem`が入りました。

個別にモジュールを入れ、利用もそうすればよいというのはあるのですが、以下が気になっています。

1. `runtimepath`に`vital.vim`と自分のプラグインが入っている状態で、`Mt19937ar`、`Xor128`よりアルファベットで前の名前だった場合にそれがデフォルトインストールされますが、これは意図したものでしょうか。逆に最初の1つになるもの以外は入りませんが、これもですか?
2. その時の名前で他の`Generator`がある場合もデフォルト利用されますか? (たぶんされる)
3. 2.を抑制する方法はありますか?
4. 1-3的なこととは別で、デフォルトで入るのを抑制し、個別の一つだけ入れる方法はありますか?

(ソース的にはどれもたぶん無理ではないか、とも思っています)

そしてこれらは意図した所でしょうか?

**Comment by thinca** [comment]
`Random` モジュールは Generator が最低1つ必要であるため、どれか1つに依存、と言う形にしていました。どれが選択されるかはあまり考えられていません。
意図的に1つ選んで入れれば、それ以外のものは入らない想定です。

**Comment by tsuyoshicho** [comment]
なるほど、であれば大丈夫ですね。
挙動を確認してみます。
ありがとうございます。

**Comment by tsuyoshicho** [comment]
確認できました。
ありがとうございます。
