### ISSUE TITLE
Question: DateTime policy

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vital.vim#658]
すみません、`DateTime`について教えてください。

現在、unix_time()で返すタイムスタンプは2038 年までになっていますが、これは32bit unix epochの上限ですよね。

これに制限している理由は何なのでしょうか?

64bitとその制限が近づいてきたことを考えると、vim自体はまだとはいえ、この関数では「num64下である」などの条件付きで64bit unix epochの限界値まで対応してもよいのでないか、と思うのですが...

**Comment by thinca** [comment]
良さそう。

**Comment by tsuyoshicho** [comment]
リンクしてるOTPのモジュールのRFCのテストに2603年だかを指定するものがあって発覚しました。
[RFC 6238 \- TOTP: Time\-Based One\-Time Password Algorithm](https://tools.ietf.org/html/rfc6238#page-14)

自分でも修正の検討は考えてみますが、だいぶ遅くなりそうです

**Comment by tsuyoshicho** [comment]
ぱっと先に確認できるだけしたところ

* strftimeは桁大きくても大丈夫でした `echo strftime('%Y %m %d %H %M %S', 20000000000)` で `2603 10 11 20 33 20`
* 2038でブロックしているのは次の所くらい?

```vim
 function! s:DateTime.unix_time() abort
  if !has_key(self, '__unix_time')
    if self._year < 1969 || 2038 < self._year
      let self.__unix_time = -1
```

の場合はここだけnum64で条件チェック(64bitだと100億年くらいいけるようなので、上限なし?)すれば対応できるかな...
