### ISSUE TITLE
Random: s:next() is not defined anywhere

### ISSUE THREAD

**Issue by ujihisa** [vim-jp/vital.vim#663]
@thinca 

https://github.com/vim-jp/vital.vim/blob/master/autoload/vital/__vital__/Random.vim#L108 this `s:next` is not defined anywhere. So if Vim runtime evaluate this expression it always throws an error.

**Comment by tsuyoshicho** [comment]
@ujihisa @thinca 

I think below, Is this correct?:

`Randowm.new()` 's `s:next()` call case

1. First global random object create: currently set `s:make_seed()`, do no call `s:next()` https://github.com/vim-jp/vital.vim/blob/8217d6fc3f59b6ce43b3cb0655cf59db5f42c52f/autoload/vital/__vital__/Random.vim#L140
2. Random object create:
  a. seed arg do not set: call `s:next()` defined macro and call global random object `Random.next()` https://github.com/vim-jp/vital.vim/blob/8217d6fc3f59b6ce43b3cb0655cf59db5f42c52f/autoload/vital/__vital__/Random.vim#L145-L152
  b. seed arg set: do not call `s:next()`

When if care this function call?

```vim
  " only first global random object creation care?
  let seed = 2 <= a:0 ? a:2 : !exists('s:common_random') ? s:make_seed() : s:next()
```

**Comment by thinca** [comment]
@tsuyoshicho Yes, it is correct.

**Comment by ujihisa** [comment]
:goodpoem: https://github.com/vim-jp/vital.vim/pull/671
