### ISSUE TITLE
Security Update need : codecov Bash Uploader

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vital.vim#770]
https://github.com/vim-jp/vital.vim/blob/5828301d6bae0858e9ea21012913544f5ef8e375/scripts/coverage.sh#L22

ここについて

[Introducing Codecov's New Uploader \- Codecov](https://about.codecov.io/blog/introducing-codecovs-new-uploader/)

として 

> Bash Uploader Deprecation Plan
> With the Uploader released, the Bash Uploader will now undergo the following deprecation plan:
>
>   Jun 1, 2021, to Sept 1, 2021: Codecov will make multiple reminder announcements via our blog and our email newsletter concerning the deprecation plan for the Bash Uploader. Those announcements will contain this deprecation plan. 
>   Sept 1, 2021, to Nov 1, 2021: Codecov will conduct scheduled brownouts of the Bash Uploader. At predetermined times throughout the week, the Bash Uploader will not function. These brownout periods will initially have at least a one-week notice, before occurring but advanced notice times will decrease throughout this three-month period. Each brownout period will be publicly broadcast to users, though.
>   Nov 1, 2021, to Feb 1, 2022: Codecov will conduct random unscheduled brownouts of the Bash Uploader. With no announcement or prior disclosure, the Bash Uploader will not function. 
>   Feb 1, 2022, and onward: The Bash Uploader will be fully sunset and will no longer function.

利用が不可になる

#701 ではGHAのuploaderを使うようにしているので問題はないはず...

**Comment by thinca** [comment]
#701 を見ましたが、`codecov/codecov-action@v1`  を使ってるみたいですね。実は v1 はまさにこの Bash アップローダーを叩いているだけ(だったはず、確か…)で、すでに Deprecated になっています :cold_sweat:

https://github.com/codecov/codecov-action
README に v2 への移行方法が載っています。

**Comment by tsuyoshicho** [comment]
以前見て内部的には利用しているの知っていたので、確認不足でした。
数日中にはv2対応します。

**Comment by tsuyoshicho** [comment]
マージされたのでclose
