### ISSUE TITLE
LasyList.take() の挙動が一致していない

### ISSUE THREAD

**Issue by syngan** [vim-jp/vital.vim#93]
先に spec を追加してしまいましたが。
`from_list()` と `iterator()` の `take()` の挙動が `file_readlines()` のそれと異なっていますが、仕様でしょうか？

``` vim
let x = LL.file_readlines('長いぜ.txt')
echo LL.take(3, x)
echo LL.take(20, x)
echo LL.take(10, x)[5:] " 5..10の取得
```

とすると、3行目まで, 4行目から 23 行目まで, ... という風にリストが構築されますが、

``` vim
let a = [1,2,3,4,5,6,7,8,9,10]
let b = g:LL.iterate(1, 'v:val + 1')
echo g:LL.take(1, b)
echo g:LL.take(1, b)
echo g:LL.take(1, b) 
```

と、`take()` をしてもずっと `[1]` が得られます。 `from_list()` で構築した LazyList の場合も同様
- spec は file_readlines() の動作に従って書きました。

**Comment by ujihisa** [comment]
新しく入ったStream by @tyru がLazyListを置き換えれそうなので、これは閉じますー

**Comment by tyru** [comment]
:smile:
